SELECT DISTINCT
    -- 🔹 Identificación del paciente
    GENPACIEN.PACNUMDOC AS DOCUMENTO,
    CASE GENPACIEN.PACTIPDOC 
        WHEN 1 THEN 'CC' WHEN 2 THEN 'CE' WHEN 3 THEN 'TI' WHEN 4 THEN 'RC'
        WHEN 5 THEN 'PA' WHEN 6 THEN 'AS' WHEN 7 THEN 'MS' WHEN 8 THEN 'NU'
        WHEN 10 THEN 'CN' WHEN 12 THEN 'PE' WHEN 14 THEN 'PE' WHEN 15 THEN 'PE'
        WHEN 9 THEN 'PE' ELSE 'NONE' 
    END AS TIPO_DOC,

    -- 🔹 Datos personales
    GENPACIEN.PACPRIAPE AS APELLIDO1,
    GENPACIEN.PACSEGAPE AS APELLIDO2,
    GENPACIEN.PACPRINOM AS NOMBRE1,
    GENPACIEN.PACSEGNOM AS NOMBRE2,
    FORMAT(GENPACIEN.GPAFECNAC, 'yyyy-MM-dd', 'en-us') AS FECHA_NAC,
    GENPAISES.GPACODNUM AS A_34_PAIS,

    -- 🔹 Direcciones
    TRY_CAST(adinfpaci AS XML).value('(/HCCLInfoPaciente/@DIRECC)[1]', 'nvarchar(400)') AS [DIRECCION],

	GENMUNICI.MUNNOMMUN AS MUNICIPIO,

	CASE GENBARRIO.GEBZONAUR  
        WHEN 0 THEN 'U' WHEN 1 THEN 'R'  ELSE 'NONE' 
    END AS TIPO_ZONA,

    -- 🔹 Información administrativa y socioeconómica
    GENTERCER.TERNOMCOM AS EAPB,
    GENOCUPACION.DGONOMBRE AS OCUPACION,

    -- 🔹 Clasificación de etnia
    CASE 
        WHEN ADNGRUETN.ADGECODIGO IS NULL THEN 6
        WHEN ADNGRUETN.ADGECODIGO = 06 THEN 5
        WHEN ADNGRUETN.ADGECODIGO = 07 THEN 6
        WHEN ADNGRUETN.ADGECODIGO = 05 THEN 5
        ELSE ADNGRUETN.ADGGRUETN
    END AS ETNIA,

    -- 🔹 Nivel educativo (codificado)
    CASE 
        WHEN GENCARGO.GCACODIGO IS NULL THEN 13
        WHEN GENCARGO.GCACODIGO = 005 THEN 1
        WHEN GENCARGO.GCACODIGO = 006 THEN 2
        WHEN GENCARGO.GCACODIGO = 007 THEN 3
        WHEN GENCARGO.GCACODIGO = 008 THEN 4
        WHEN GENCARGO.GCACODIGO = 009 THEN 5
        WHEN GENCARGO.GCACODIGO = 010 THEN 6
        WHEN GENCARGO.GCACODIGO = 011 THEN 7
        WHEN GENCARGO.GCACODIGO = 012 THEN 8
        WHEN GENCARGO.GCACODIGO = 003 THEN 8
        WHEN GENCARGO.GCACODIGO = 013 THEN 9
        WHEN GENCARGO.GCACODIGO = 001 THEN 9
        WHEN GENCARGO.GCACODIGO = 002 THEN 10
        WHEN GENCARGO.GCACODIGO = 014 THEN 10
        WHEN GENCARGO.GCACODIGO = 015 THEN 11
        WHEN GENCARGO.GCACODIGO = 016 THEN 12
        WHEN GENCARGO.GCACODIGO = 999 THEN 13
        WHEN GENCARGO.GCACODIGO = 004 THEN 13
        ELSE 100
    END AS NIVEL_EDUCATIVO,

    -- 🔹 Datos clínicos y de atención
    GENARESER.GASNOMBRE AS INSTANCIA_ACTUAL,
    ADNINGRESO.AINTELACU AS TELEFONO,

    FORMAT(HCMHC67.HCCM05N312, 'yyyy-MM-dd', 'en-us') AS FECHA_PROBABLE_PARTO,
    HCMHC25.HCCM01N48 AS TA_SISTOLICA,
    HCMHC25.HCCM01N45 AS TA_DIASTOLICA,
    HCMHC25.HCCM01N75 AS IMC,
    HCMHC25.HCCM01N43 AS FRECUENCIA_RESPIRATORIA,
    HCMHC25.HCCM01N44 AS FRECUENCIA_CARDIACA,
    HCMHC25.HCCM01N47 AS SPO2_OXIGENO,
    HCMHC25.HCCM01N46 AS TEMPERATURA,
    HCNFOLIO.HCFECFOL AS FECHA_FOLIO

FROM ADNINGRESO
    INNER JOIN HCNFOLIO ON HCNFOLIO.ADNINGRESO = ADNINGRESO.OID
    INNER JOIN GENPACIEN ON HCNFOLIO.GENPACIEN = GENPACIEN.OID
    INNER JOIN HCMHC25 ON HCMHC25.HCNFOLIO = HCNFOLIO.OID
    LEFT JOIN HCMHC67 ON HCMHC67.HCNFOLIO = HCNFOLIO.OID
    LEFT JOIN GENDETCON ON GENPACIEN.GENDETCON = GENDETCON.OID
    LEFT JOIN GENTERCER ON GENDETCON.GENTERCER1 = GENTERCER.OID
    LEFT JOIN GENOCUPACION ON GENPACIEN.GENOCUPACION = GENOCUPACION.OID
    LEFT JOIN GENPAISES ON GENPACIEN.GENPAIS = GENPAISES.OID
    LEFT JOIN GENARESER ON HCNFOLIO.GENARESER = GENARESER.OID
    LEFT JOIN GENCARGO ON GENPACIEN.GENCARGO1 = GENCARGO.OID
    LEFT JOIN ADNGRUETN ON GENPACIEN.ADNGRUETN = ADNGRUETN.ADGGRUETN
	LEFT JOIN GENBARRIO ON GENPACIEN.GENBARRIO = GENBARRIO.OID
	LEFT JOIN GENMUNICI ON GENPACIEN.DGNMUNICIPIO = GENMUNICI.OID


-- 🔹 Filtros
WHERE
    HCNFOLIO.HCFECFOL BETWEEN CONVERT(DATETIME, '2025-10-01', 120)
    AND CONVERT(DATETIME, '2025-10-16', 120)
    AND GENPACIEN.PACNUMDOC IN ('100285788', '1002922906')