SELECT DISTINCT
    'CAUCA' AS [Departamento UPGD],
    'POPAYAN' AS [Municipio UPGD],
    'HOSPITAL UNIVERITARIO SAN JOSE' AS [Nombre UPGD],
    GENARESER.GASNOMBRE AS [Servicio],
    FORMAT(ADNINGRESO.AINFECING, 'dd/MM/yyyy', 'en-us') AS [fec_Cons (DD/MM/AAAA)],

    -- Datos personales
    GENPACIEN.PACPRINOM AS [Pri_nom],
    GENPACIEN.PACSEGNOM AS [Seg_nom],
    GENPACIEN.PACPRIAPE AS [Pri_apel],
    GENPACIEN.PACSEGAPE AS [Seg_apel],
    CASE GENPACIEN.PACTIPDOC
        WHEN 1 THEN 'CC' WHEN 2 THEN 'CE' WHEN 3 THEN 'TI' WHEN 4 THEN 'RC'
        WHEN 5 THEN 'PA' WHEN 6 THEN 'AS' WHEN 7 THEN 'MS' WHEN 8 THEN 'NU'
        WHEN 9 THEN 'PE' WHEN 10 THEN 'CN'
        WHEN 12 THEN 'PE' WHEN 14 THEN 'PE' WHEN 15 THEN 'PE'
        ELSE 'NONE'
    END AS [Tipo_ID (RC, MSI, PE, CE, CN, PT, DE)],
    GENPACIEN.PACNUMDOC AS [Num_ID],
    FORMAT(GENPACIEN.GPAFECNAC, 'dd/MM/yyyy', 'en-us') AS [fec_Naci (DD/MM/AAAA)],
    CASE 
        WHEN GENPACIEN.GPASEXPAC = 1 THEN 'M'
        WHEN GENPACIEN.GPASEXPAC = 2 THEN 'F'
        ELSE NULL
    END AS [Sexo (M, F)],

    -- Datos de residencia y afiliación
    ADNGRUETN.ADGENOMBRE AS [Pertenencia Etnia (INDÍGENA, ROM, GITANO, RAIZAL, PALENQUERO, NEGRO MULATO O AFROCOLOMBIANO, NINGUNO)],
    ' ' AS [Nom_grupo indígena (WAYUU, KOGUI, WIWA)],
    GENMUNICI.MUNNOMMUN AS [Mun_residencia],
    TRY_CAST(adinfpaci AS XML).value('(/HCCLInfoPaciente/@DIRECC)[1]', 'nvarchar(400)') AS [Dirección],
    TRY_CAST(adinfpaci AS XML).value('(/HCCLInfoPaciente/@TELEF)[1]', 'nvarchar(400)') AS [Teléfono],

    CASE 
        WHEN GENDETCON.GDEPOSSUB = 1 THEN 'SUBSIDIADO'
        WHEN GENDETCON.GDEPOSSUB = 0 THEN 'CONTRIBUTIVO'
        ELSE ''
    END AS [Tip_reg (CONTRIBUTIVO, SUBSIDIADO, INDETERMINADO, ESPECIAL, EXCEPCIÓN, NO ASEGURADO)],

    GENTERCER.TERNOMCOM AS [Afiliación (EAPB)],

    -- Datos antropométricos
    COALESCE(
        HCMHC01.HCCM00N113, HCMHC08.HCCM01N214, HCMHC104.HCCM01N01,
        HCMHC26.HCCM01N75,  HCMHC30.HCCM01N96,  HCMHC36.HCCM01N03,
        HCMHC42.HCCM01N123, HCMHC45.HCCM01N744, HCMHC45B.HCCM01N136,
        HCMHC45C.HCCM01N08, HCMHC77.HCCM01N96,  HCMHC95.HCCM01N01
    ) AS [Peso (Kg)],

    COALESCE(
        HCMHC01.HCCM00N114, HCMHC08.HCCM01N215, HCMHC104.HCCM01N02,
        HCMHC26.HCCM01N76,  HCMHC30.HCCM01N97,  HCMHC36.HCCM01N57,
        HCMHC42.HCCM01N131, HCMHC45.HCCM01N742, HCMHC45B.HCCM01N137,
        HCMHC45C.HCCM01N06, HCMHC77.HCCM01N97,  HCMHC95.HCCM01N02
    ) AS [Talla (Cm)],

    '' AS [Per_braq (cm) - Únicamente niño de 6 a 59 meses],
    '' AS [Edema (SI, NO)],

    -- Diagnóstico
    GENDIAGNO.DIANOMBRE AS [Antecedentes/Comorbilidades],
    HCNTIPHIS.HCCODIGO AS COD_SUBAREA,
    HCNTIPHIS.HCNOMBRE AS NOMBRE_SUBAREA,

    -- Fechas
    FORMAT(ADNINGRESO.AINFECING, 'yyyy-MM-dd', 'en-us') AS FECHA_INGRESO,
    FORMAT(ADNINGRESO.AINFECEGRE, 'dd/MM/yyyy HH:mm:ss', 'en-us') AS AH_FECHA_SALIDA,

    -- Códigos adicionales
    GENDIAGNO.DIACODIGO,
    GENDIAGNO.DIANOMBRE

FROM ADNINGRESO
    INNER JOIN HCNFOLIO ON HCNFOLIO.ADNINGRESO = ADNINGRESO.OID
    INNER JOIN GENPACIEN ON HCNFOLIO.GENPACIEN = GENPACIEN.OID
    LEFT JOIN HCNDIAPAC ON HCNFOLIO.OID = HCNDIAPAC.HCNFOLIO
    LEFT JOIN GENMUNICI ON GENPACIEN.DGNMUNICIPIO = GENMUNICI.OID
    LEFT JOIN GENDETCON ON GENPACIEN.GENDETCON = GENDETCON.OID
    LEFT JOIN GENARESER ON HCNFOLIO.GENARESER = GENARESER.OID
    LEFT JOIN GENTERCER ON GENDETCON.GENTERCER1 = GENTERCER.OID
    LEFT JOIN ADNGRUETN ON GENPACIEN.ADNGRUETN = ADNGRUETN.ADGGRUETN
    LEFT JOIN HCMHC01   ON HCMHC01.HCNFOLIO = HCNFOLIO.OID
    LEFT JOIN HCMHC08   ON HCMHC08.HCNFOLIO = HCNFOLIO.OID
    LEFT JOIN HCMHC104  ON HCMHC104.HCNFOLIO = HCNFOLIO.OID
    LEFT JOIN HCMHC26   ON HCMHC26.HCNFOLIO = HCNFOLIO.OID
    LEFT JOIN HCMHC30   ON HCMHC30.HCNFOLIO = HCNFOLIO.OID
    LEFT JOIN HCMHC36   ON HCMHC36.HCNFOLIO = HCNFOLIO.OID
    LEFT JOIN HCMHC42   ON HCMHC42.HCNFOLIO = HCNFOLIO.OID
    LEFT JOIN HCMHC45   ON HCMHC45.HCNFOLIO = HCNFOLIO.OID
    LEFT JOIN HCMHC45B  ON HCMHC45B.HCNFOLIO = HCNFOLIO.OID
    LEFT JOIN HCMHC45C  ON HCMHC45C.HCNFOLIO = HCNFOLIO.OID
    LEFT JOIN HCMHC77   ON HCMHC77.HCNFOLIO = HCNFOLIO.OID
    LEFT JOIN HCMHC95   ON HCMHC95.HCNFOLIO = HCNFOLIO.OID
    LEFT JOIN GENDIAGNO ON GENDIAGNO.OID = HCNDIAPAC.GENDIAGNO
    LEFT JOIN HCNTIPHIS ON HCNFOLIO.HCNTIPHIS = HCNTIPHIS.OID

WHERE
    HCNFOLIO.HCFECFOL BETWEEN 
        CONVERT(DATETIME, '2025-10-23 00:00:00', 120) 
        AND CONVERT(DATETIME, '2025-10-30 00:00:00', 120)
    AND (
        DATEDIFF(YEAR, GENPACIEN.GPAFECNAC, ADNINGRESO.AINFECING)
        - CASE
            WHEN (MONTH(GENPACIEN.GPAFECNAC) > MONTH(ADNINGRESO.AINFECING)
                OR (MONTH(GENPACIEN.GPAFECNAC) = MONTH(ADNINGRESO.AINFECING)
                    AND DAY(GENPACIEN.GPAFECNAC) > DAY(ADNINGRESO.AINFECING)))
            THEN 1 ELSE 0 
          END
    ) <= 5
    AND COALESCE(
        HCMHC01.HCCM00N113, HCMHC08.HCCM01N214, HCMHC104.HCCM01N01,
        HCMHC26.HCCM01N75,  HCMHC30.HCCM01N96,  HCMHC36.HCCM01N03,
        HCMHC42.HCCM01N123, HCMHC45.HCCM01N744, HCMHC45B.HCCM01N136,
        HCMHC45C.HCCM01N08, HCMHC77.HCCM01N96,  HCMHC95.HCCM01N01,
        HCMHC01.HCCM00N114, HCMHC08.HCCM01N215, HCMHC104.HCCM01N02,
        HCMHC26.HCCM01N76,  HCMHC30.HCCM01N97,  HCMHC36.HCCM01N57,
        HCMHC42.HCCM01N131, HCMHC45.HCCM01N742, HCMHC45B.HCCM01N137,
        HCMHC45C.HCCM01N06, HCMHC77.HCCM01N97,  HCMHC95.HCCM01N02
    ) IS NOT NULL;
