-- CONSULTA RELACIONADA DONDE SE EXTRAEN CIE 10 CARDIOLOGICOS POR MES
-- PERIOCIDAD EL PRIMERO DE CADA MES
-- urgenciasadultos Hospital 
-- urgenciasadultos@hospitalsanjose.gov.co

WITH IngresosFiltrados AS (
    SELECT DISTINCT *
    FROM ADNINGRESO
    WHERE AINFECING >= CONVERT(datetime, '2026-01-01', 120) AND AINFECING < CONVERT(datetime, '2026-01-08', 120))
SELECT DISTINCT
    ING.AINCONSEC AS INGRESO
	, GENPACIEN.PACNUMDOC AS [HISTORIA]
	, GENPACIEN.GPANOMCOM AS NOMBRES
	, DATEDIFF(YEAR, GENPACIEN.GPAFECNAC, ING.AINFECING)
		- CASE WHEN (MONTH(GENPACIEN.GPAFECNAC) > MONTH(ING.AINFECING)
		OR (MONTH(GENPACIEN.GPAFECNAC) = MONTH(ING.AINFECING) AND DAY(GENPACIEN.GPAFECNAC) > DAY(ING.AINFECING)))
		THEN 1 ELSE 0 END AS EDAD
	, CASE WHEN GENPACIEN.GPASEXPAC = 1 THEN 'MASCULINO' WHEN GENPACIEN.GPASEXPAC = 2 THEN 'FEMENINO' ELSE NULL END AS GENERO
	, GENDIAGNO.DIACODIGO AS COD_DAT
	, GENDIAGNO.DIANOMBRE AS NAM_DAT
	, CASE WHEN HCNDIAPAC.HCPDIAPRIN = 1 THEN 'PRINCIPAL' WHEN HCNDIAPAC.HCPDIAPRIN = 0 THEN 'SEC' ELSE '' END AS TIP_COD_DAT
	, FORMAT(ING.AINFECING, 'yyyy-MM-dd HH:mm') AS [FECHA_INGRESO]
	, FORMAT(ING.AINFECEGRE, 'yyyy-MM-dd HH:mm') AS [FECHA_EGRESO]
	, DAIN.DIACODIGO AS [COD DX INGRESO]
	, DAIN.DIANOMBRE AS [DIAGNOSTICO INGRESO]
	, DA.DIACODIGO AS [COD DX EGRESO]
	, DA.DIANOMBRE AS [DIAGNOSTICO EGRESO]
FROM IngresosFiltrados ING
	INNER JOIN HCNFOLIO ON HCNFOLIO.ADNINGRESO = ING.OID
	INNER JOIN GENPACIEN ON HCNFOLIO.GENPACIEN = GENPACIEN.OID
	INNER JOIN HCNDIAPAC ON HCNFOLIO.OID = HCNDIAPAC.HCNFOLIO
	INNER JOIN GENDIAGNO ON GENDIAGNO.OID = HCNDIAPAC.GENDIAGNO
    AND GENDIAGNO.DIACODIGO LIKE 'I2%'
    -- el filtrado de HCPDIAPRIN se hace abajo para el tipo de código
LEFT JOIN primer_folio pf ON pf.oidingreso = ING.oid

-- Diagnóstico en folio de ingreso (si existe)
OUTER APPLY (
    SELECT TOP (1) 
		g.DIACODIGO, g.DIANOMBRE
    FROM primer_folio
		JOIN HCNFOLIO hf2 ON hf2.OID = primer_folio.folio
		JOIN HCNDIAPAC h2 ON h2.HCNFOLIO = hf2.OID
		JOIN GENDIAGNO g ON g.OID = h2.GENDIAGNO
		AND g.DIACODIGO LIKE 'I2%'
    WHERE primer_folio.oidingreso = ING.oid
		--AND g.DIACODIGO LIKE 'I2%'
) DAIN

-- Diagnóstico en folio de egreso (si existe)
OUTER APPLY (
    SELECT TOP (1) g.DIACODIGO, g.DIANOMBRE
    FROM ADNEGRESO ae
		JOIN ADNDIAEGR de ON de.ADNEGRESO = ae.OID
		JOIN GENDIAGNO g ON g.OID = de.DIACODIGO
		AND g.DIACODIGO LIKE 'I2%'
    WHERE ae.OID = ING.ADNEGRESO
		--AND g.DIACODIGO LIKE 'I2%'
) DA

WHERE HCNDIAPAC.HCPDIAPRIN = 1
	AND GENDIAGNO.DIACODIGO LIKE 'I2%'
	AND ING.AINFECEGRE IS NOT NULL;