-- CONSULTAS

WITH ConsultasUnicas AS (
    SELECT
        GENPACIEN.PACNUMDOC AS HISTORIA,
        CONVERT(VARCHAR, CONVERT(DATE, GENPACIEN.GPAFECNAC), 120) AS FECHA_NACIMIENTO,

        GENPACIEN.PACPRINOM + ' ' + 
        ISNULL(GENPACIEN.PACSEGNOM + ' ', '') + 
        GENPACIEN.PACPRIAPE + ' ' + 
        ISNULL(GENPACIEN.PACSEGAPE, '') AS NOMBRE_COMPLETO,

        GENDIAGNO.DIACODIGO AS DX,
        CASE 
            WHEN HCNDIAPAC.HCPDIAPRIN = 1 THEN 'PRINCIPAL' 
            WHEN HCNDIAPAC.HCPDIAPRIN = 0 THEN 'SECUNDARIO' 
            ELSE 'OTRO' 
        END AS TIPO_DX,
        GENDIAGNO.DIANOMBRE AS DIAGNOSTICO,
        GENSERIPS.SIPNOMBRE AS PROCEDIMIENTO,
        GENMEDICO1.GMENOMCOM AS MEDICO,
        GENESPECI1.GEEDESCRI AS ESPECIALIDAD,

        CONVERT(VARCHAR, HCNFOLIO.HCFECFOL, 120) AS FECHA_FOLIO_HC,
        HCNFOLIO.OID AS FOLIO,
        CONVERT(VARCHAR, SLNFACTUR.SFAFECFAC, 120) AS FECHA_FACTURACION,
        SLNFACTUR.SFANUMFAC AS NUMERO_FACTURA,
        CONVERT(VARCHAR, SLNSERPRO.SERFECSER, 120) AS FECHA_SERVICIO,
        CONVERT(VARCHAR, ADNINGRESO.AINFECING, 120) AS FECHA_INGRESO,
        ADNINGRESO.AINCONSEC AS CONSECUTIVO_INGRESO,
        GENDETCON.GDENOMBRE AS ENTIDAD,

        ROW_NUMBER() OVER (
            PARTITION BY GENPACIEN.PACNUMDOC
            ORDER BY HCNFOLIO.HCFECFOL DESC
        ) AS RN
    FROM HCNFOLIO
    INNER JOIN GENMEDICO ON GENMEDICO.OID = HCNFOLIO.GENMEDICO
    INNER JOIN GENPACIEN ON GENPACIEN.OID = HCNFOLIO.GENPACIEN
    INNER JOIN SLNFACTUR ON HCNFOLIO.ADNINGRESO = SLNFACTUR.ADNINGRESO
    INNER JOIN ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO AND ADNINGRESO.GENPACIEN = HCNFOLIO.GENPACIEN
    INNER JOIN SLNSERPRO ON SLNFACTUR.ADNINGRESO = SLNSERPRO.ADNINGRES1
    INNER JOIN GENMEDICO GENMEDICO1 ON GENMEDICO1.OID = SLNSERPRO.GENMEDICO1
    INNER JOIN GENESPECI GENESPECI1 ON GENESPECI1.OID = SLNSERPRO.DGNESPECI1
    INNER JOIN SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
    INNER JOIN SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1 AND SLNORDSER.SOSESTADO = 1
    INNER JOIN GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1 AND GENSERIPS.SIPNOMBRE LIKE '%CONSU%'
    INNER JOIN GENESPECI ON HCNFOLIO.GENESPECI = GENESPECI.OID
    INNER JOIN GENMUNICI ON GENMUNICI.OID = GENPACIEN.DGNMUNICIPIO
    INNER JOIN GENDEPTO ON GENDEPTO.OID = GENMUNICI.GENDEPTO
    INNER JOIN GENDETCON ON SLNFACTUR.GENDETCON = GENDETCON.OID
    INNER JOIN TIPOPLANBENEFICIOS ON TIPOPLANBENEFICIOS.ID = GENDETCON.GDECONFAC
    INNER JOIN HCNDIAPAC ON HCNFOLIO.OID = HCNDIAPAC.HCNFOLIO
    INNER JOIN GENDIAGNO ON GENDIAGNO.OID = HCNDIAPAC.GENDIAGNO
    WHERE 
        HCNFOLIO.HCFECFOL BETWEEN CONVERT(DATETIME, '2025-10-29 00:00:00', 120) AND CONVERT(DATETIME, '2025-10-30 00:00:00', 120)
        AND (LOWER(GENDIAGNO.DIACODIGO) LIKE '%c%' OR LOWER(GENDIAGNO.DIACODIGO) LIKE '%d%')
        AND (LOWER(GENDETCON.GDENOMBRE) LIKE '%NUEVA%')
)

SELECT *
FROM ConsultasUnicas
WHERE RN = 1;