-- DATOS PERSONALES MAS RECIENTES
WITH MaxEdadPorDocumento AS (
    SELECT 
        GENPACIEN.PACNUMDOC,
        MAX(
            DATEDIFF(YEAR, GENPACIEN.GPAFECNAC, ADNINGRESO.AINFECING) -
            CASE 
                WHEN (MONTH(GENPACIEN.GPAFECNAC) > MONTH(ADNINGRESO.AINFECING) 
                   OR (MONTH(GENPACIEN.GPAFECNAC) = MONTH(ADNINGRESO.AINFECING) 
                   AND DAY(GENPACIEN.GPAFECNAC) > DAY(ADNINGRESO.AINFECING))) 
                THEN 1 ELSE 0 
            END
        ) AS MaxEdad
    FROM ADNINGRESO
    INNER JOIN HCNFOLIO ON HCNFOLIO.ADNINGRESO = ADNINGRESO.OID
    INNER JOIN GENPACIEN ON HCNFOLIO.GENPACIEN = GENPACIEN.OID
    WHERE GENPACIEN.PACNUMDOC = '1060876230'
    GROUP BY GENPACIEN.PACNUMDOC
)

SELECT DISTINCT
    DATEDIFF(YEAR, GENPACIEN.GPAFECNAC, ADNINGRESO.AINFECING) -
    CASE 
        WHEN (MONTH(GENPACIEN.GPAFECNAC) > MONTH(ADNINGRESO.AINFECING) 
           OR (MONTH(GENPACIEN.GPAFECNAC) = MONTH(ADNINGRESO.AINFECING) 
           AND DAY(GENPACIEN.GPAFECNAC) > DAY(ADNINGRESO.AINFECING))) 
        THEN 1 ELSE 0 
    END AS A_A_EDAD,
    GEENENTADM.ENTCODIGO AS AF_COD_EAPB,
    GEENENTADM.ENTNOMBRE AS AF_ENTIDAD,
    CASE GENPACIEN.GPATIPPAC
        WHEN 0 THEN 'NINGUNO'
        WHEN 1 THEN 'CONTRIBUTIVO'
        WHEN 2 THEN 'SUBSIDIADO'
        WHEN 3 THEN 'VINCULADO'
        WHEN 4 THEN 'PARTICULAR'
        WHEN 5 THEN 'OTRO'
        WHEN 6 THEN 'DESPLAZADO CONTRIBUTIVO'
        WHEN 7 THEN 'DESPLAZADO SUBSIDIADO'
        WHEN 8 THEN 'DESPLAZADO NO ASEGURADO' 
    END as AF_TIP_CONVE,
    A_0_TR=2, A_1_CON=1, A_2_CIPS='190010003101',
    CASE GENPACIEN.PACTIPDOC
        WHEN 1 THEN 'CC' WHEN 2 THEN 'CE' WHEN 3 THEN 'TI'
        WHEN 4 THEN 'RC' WHEN 5 THEN 'PA' WHEN 6 THEN 'AS'
        WHEN 7 THEN 'MS' WHEN 8 THEN 'NU' WHEN 10 THEN 'CN'
        WHEN 12 THEN 'PE' WHEN 14 THEN 'PE' WHEN 15 THEN 'PE' 
        WHEN 9 THEN 'PE'
        ELSE 'NONE' 
    END AS A_3_TIPODOC,
    GENPACIEN.PACNUMDOC AS A_4_Número,
    -- nombres y apellidos
    CASE WHEN TRIM(GENPACIEN.PACPRIAPE) = '' THEN 'NONE'
        ELSE REPLACE(TRANSLATE(TRIM(GENPACIEN.PACPRIAPE), 'áéíóúÁÉÍÓÚñÑ', 'aeiouAEIOUNN'), ' ', '')
    END AS A_5_APELLIDO1,
    CASE WHEN TRIM(GENPACIEN.PACSEGAPE) = '' THEN 'NONE'
        ELSE REPLACE(TRANSLATE(TRIM(GENPACIEN.PACSEGAPE), 'áéíóúÁÉÍÓÚñÑ', 'aeiouAEIOUNN'), ' ', '')
    END AS A_6_APELLIDO2,
    CASE WHEN TRIM(GENPACIEN.PACPRINOM) = '' THEN 'NONE'
        ELSE REPLACE(TRANSLATE(TRIM(GENPACIEN.PACPRINOM), 'áéíóúÁÉÍÓÚñÑ', 'aeiouAEIOUNN'), ' ', '')
    END AS A_7_NOMBRE1,
    CASE WHEN TRIM(GENPACIEN.PACSEGNOM) = '' THEN 'NONE'
        ELSE REPLACE(TRANSLATE(TRIM(GENPACIEN.PACSEGNOM), 'áéíóúÁÉÍÓÚñÑ', 'aeiouAEIOUNN'), ' ', '')
    END AS A_8_NOMBRE1,
    FORMAT(GENPACIEN.GPAFECNAC, 'yyyy-MM-dd', 'en-us') AS A_9_NACIMIENTO,
    CASE WHEN GENPACIEN.GPASEXPAC = 1 THEN 'M' 
         WHEN GENPACIEN.GPASEXPAC = 2 THEN 'F' 
         ELSE NULL 
    END AS A_10_SEXO,
    CASE 
        WHEN ADNGRUETN.ADGECODIGO IS NULL THEN 6
        WHEN ADNGRUETN.ADGECODIGO IN (5, 6, 7) THEN 5
        ELSE ADNGRUETN.ADGGRUETN
    END AS A_11_ETNIA,
    GENOCUPACION.DGOCODIGO AS A_12_OCUPACION,
    GENOCUPACION.DGONOMBRE,
    CASE 
        WHEN GENCARGO.GCACODIGO IS NULL THEN 13
        WHEN GENCARGO.GCACODIGO IN (5) THEN 1
        WHEN GENCARGO.GCACODIGO IN (6) THEN 2
        WHEN GENCARGO.GCACODIGO IN (7) THEN 3
        WHEN GENCARGO.GCACODIGO IN (8) THEN 4
        WHEN GENCARGO.GCACODIGO IN (9) THEN 5
        WHEN GENCARGO.GCACODIGO IN (10) THEN 6
        WHEN GENCARGO.GCACODIGO IN (11) THEN 7
        WHEN GENCARGO.GCACODIGO IN (3,12) THEN 8
        WHEN GENCARGO.GCACODIGO IN (1,13) THEN 9
        WHEN GENCARGO.GCACODIGO IN (2,14) THEN 10
        WHEN GENCARGO.GCACODIGO = 15 THEN 11
        WHEN GENCARGO.GCACODIGO = 16 THEN 12
        WHEN GENCARGO.GCACODIGO IN (999, 4) THEN 13
        ELSE 100
    END AS A_13_NIV_EDUC,
    GENPAISES.GPACODNUM AS A_34_PAIS
FROM ADNINGRESO
INNER JOIN HCNFOLIO ON HCNFOLIO.ADNINGRESO = ADNINGRESO.OID
INNER JOIN GENPACIEN ON HCNFOLIO.GENPACIEN = GENPACIEN.OID
LEFT JOIN ADNGRUETN ON GENPACIEN.ADNGRUETN = ADNGRUETN.ADGGRUETN
LEFT JOIN GENCARGO ON GENPACIEN.GENCARGO1 = GENCARGO.OID
LEFT JOIN GENDETCON ON GENPACIEN.GENDETCON = GENDETCON.OID
LEFT JOIN GENTERCER ON GENDETCON.GENTERCER1 = GENTERCER.OID
LEFT JOIN GENOCUPACION ON GENPACIEN.GENOCUPACION = GENOCUPACION.OID
LEFT JOIN GENPAISES ON GENPACIEN.GENPAIS = GENPAISES.OID
LEFT JOIN HCMHC35 ON HCMHC35.HCNFOLIO = HCNFOLIO.OID
LEFT JOIN GENCONTRA ON GENCONTRA.OID = GENDETCON.GENCONTRA1 
LEFT JOIN GEENENTADM ON GENCONTRA.DGNENTADM1 = GEENENTADM.OID
INNER JOIN MaxEdadPorDocumento med 
    ON med.PACNUMDOC = GENPACIEN.PACNUMDOC
    AND (
        DATEDIFF(YEAR, GENPACIEN.GPAFECNAC, ADNINGRESO.AINFECING) -
        CASE 
            WHEN (MONTH(GENPACIEN.GPAFECNAC) > MONTH(ADNINGRESO.AINFECING) 
               OR (MONTH(GENPACIEN.GPAFECNAC) = MONTH(ADNINGRESO.AINFECING) 
               AND DAY(GENPACIEN.GPAFECNAC) > DAY(ADNINGRESO.AINFECING))) 
            THEN 1 ELSE 0 
        END
    ) = med.MaxEdad
WHERE GENPACIEN.PACNUMDOC = '1060876230'