SELECT DISTINCT
	GENPACIEN.PACNUMDOC AS Documento
	, ADNINGRESO.AINCONSEC as Ingreso
	
	--DONDE SE LLENO EL DATO
    --, GENARESER.GASCODIGO [Cod Area], GENARESER.GASNOMBRE [Area]
	, HCNTIPHIS.HCCODIGO [CODIGO FOLIO], HCNTIPHIS.HCNOMBRE FOLIO
	, HCNFOLIO.HCNUMFOL [Numero Folio]
	-- RESPONSABLE DE LLENAR EL VALOR
	, GENMEDICO.GMENOMCOM [Responsable], GENESPECI.GEEDESCRI [Especialidad responsable]
	-- FECHA DE DILIGENCIAMIENTO DEL DATO
    , FORMAT(ADNINGRESO.AINFECING, 'yyyy-MM-dd', 'en-us') [Fecha Ingreso]
    , FORMAT(ADNINGRESO.AINFECEGRE, 'yyyy-MM-dd', 'en-us') [Fecha Egreso]
	, FORMAT(HCNFOLIO.HCFECFOL, 'yyyy-MM-dd hh:mm', 'en-us') [Fecha De Folio]

FROM ADNINGRESO
    INNER JOIN GENPACIEN ON ADNINGRESO.GENPACIEN = GENPACIEN.OID
	INNER JOIN HCNFOLIO ON HCNFOLIO.ADNINGRESO = ADNINGRESO.OID
	LEFT JOIN HCNDIAPAC ON HCNFOLIO.OID = HCNDIAPAC.HCNFOLIO
	LEFT JOIN GENDIAGNO ON GENDIAGNO.OID = HCNDIAPAC.GENDIAGNO
    --LEFT JOIN GENARESER on HCNFOLIO.GENARESER =  GENARESER.OID
    LEFT JOIN GENMEDICO ON HCNFOLIO.GENMEDICO = GENMEDICO.OID
    LEFT JOIN GENESPECI on HCNFOLIO.GENESPECI = GENESPECI.OID
    LEFT JOIN HCNTIPHIS on HCNFOLIO.HCNTIPHIS = HCNTIPHIS.OID

WHERE
	GENPACIEN.PACNUMDOC in ('1002957269',
'1007179251',
'1002968427',
'1061744133',
'1002957771',
'1059534524',
'1063816765',
'1061806959',
'1006514472',
'1061786809',
'1060879693')
	ORDER BY HCNFOLIO.HCNUMFOL DESC
	--AND ADNINGRESO.AINFECING BETWEEN CONVERT(DATETIME, '2026-01-01', 120) AND CONVERT(DATETIME, '2026-01-02', 120)