-- EGRESOS

WITH CTE AS (
    SELECT
        GENPACIEN.PACNUMDOC AS HISTORIA,
        GENPACIEN.GPANOMCOM AS NOMBRES,
        FORMAT(GENPACIEN.GPAFECNAC, 'yyyy-MM-dd', 'es-ES') AS FECHA_NAC,
        CASE
            WHEN GENPACIEN.GPASEXPAC = 1 THEN 'M'
            WHEN GENPACIEN.GPASEXPAC = 2 THEN 'F'
            ELSE NULL
        END AS SEXO,
        FORMAT(HCFECFOL, 'yyyy-MM-dd hh:mm', 'es-ES') AS FECHA_FOLIO,
        FORMAT(
            ADNINGRESO.AINFECING,
            'yyyy-MM-dd hh:mm',
            'es-ES'
        ) AS FECHA_INGRESO,
        CASE
            WHEN GENARESER.GASCODIGO = '7311'
            AND ISDATE(ADNINGRESO.AINFECING) = 1 THEN FORMAT(
                CAST(ADNINGRESO.AINFECING AS DATETIME),
                'yyyy-MM-dd HH:mm',
                'es-ES'
            )
            WHEN GENARESER.GASCODIGO = '7311-1'
            AND ISDATE(ADNINGRESO.AINFECING) = 1 THEN FORMAT(
                CAST(ADNINGRESO.AINFECING AS DATETIME),
                'yyyy-MM-dd HH:mm',
                'es-ES'
            )
            WHEN GENARESER.GASCODIGO = '7354-2'
            AND ISDATE(ADNINGRESO.AINFECING) = 1 THEN FORMAT(
                CAST(ADNINGRESO.AINFECING AS DATETIME),
                'yyyy-MM-dd HH:mm',
                'es-ES'
            )
            WHEN ISDATE(ADNINGRESO.AINFECEGRE) = 1 THEN FORMAT(
                CAST(ADNINGRESO.AINFECEGRE AS DATETIME),
                'yyyy-MM-dd HH:mm',
                'es-ES'
            )
            ELSE NULL -- O alguna fecha por defecto si es necesario
        END AS FECHA_EGRESO,
        GENDIAGNO.DIACODIGO AS DX,
        GENDIAGNO.DIANOMBRE AS DIAGNOSTICO,
        HCNTIPHIS.HCCODIGO,
        HCNTIPHIS.HCNOMBRE,
        HCNDIAPAC.HCPDIAPRIN,
        GENMEDICO.GMENOMCOM AS MEDICO,
        GENESPECI.GEEDESCRI,
        GENARESER.GASNOMBRE,
        
		--GENTERCER.TERNOMCOM AS ENTIDAD,
        --CASE
        --    WHEN GENDETCON.GDEPOSSUB = 1 THEN 'SUBSIDIADO'
        --    WHEN GENDETCON.GDEPOSSUB = 0 THEN 'CONTRIBUTIVO'
        --    ELSE ''
        --END AS REGIMEN,

		GEENENTADM.ENTCODIGO AS AF_COD_EAPB, GEENENTADM.ENTNOMBRE AS AF_ENTIDAD,

        ADNINGRESO.AINCONSEC AS INGRESO,
        ROW_NUMBER() OVER (
            PARTITION BY GENPACIEN.PACNUMDOC
            ORDER BY
                ADNINGRESO.AINFECING DESC
        ) AS ROW_NUM
    FROM
        ADNINGRESO
        INNER JOIN HCNFOLIO ON HCNFOLIO.ADNINGRESO = ADNINGRESO.OID
        LEFT JOIN GENPACIEN ON HCNFOLIO.GENPACIEN = GENPACIEN.OID
        INNER JOIN HCNTIPHIS ON HCNFOLIO.HCNTIPHIS = HCNTIPHIS.OID
        INNER JOIN HCNDIAPAC ON HCNFOLIO.OID = HCNDIAPAC.HCNFOLIO
        INNER JOIN GENDIAGNO ON GENDIAGNO.OID = HCNDIAPAC.GENDIAGNO
        LEFT JOIN GENDETCON ON GENPACIEN.GENDETCON = GENDETCON.OID
        INNER JOIN GENMEDICO ON HCNFOLIO.GENMEDICO = GENMEDICO.OID
        INNER JOIN GENESPECI ON HCNFOLIO.GENESPECI = GENESPECI.OID
        LEFT JOIN GENARESER ON HCNFOLIO.GENARESER = GENARESER.OID
        LEFT JOIN GENTERCER ON GENDETCON.GENTERCER1 = GENTERCER.OID

		LEFT JOIN GENCONTRA ON GENCONTRA.OID = GENDETCON.GENCONTRA1 
		LEFT JOIN GEENENTADM ON GENCONTRA.DGNENTADM1 = GEENENTADM.OID
    WHERE
        HCFECFOL BETWEEN CONVERT(DATETIME, '2026-01-27 00:00:00', 120)
        AND CONVERT(DATETIME, '2026-01-28 00:00:00', 120)
        AND (
            LOWER(GENDIAGNO.DIACODIGO) LIKE '%C%'
            OR LOWER(GENDIAGNO.DIACODIGO) LIKE '%D%'
        )

		AND LOWER(GEENENTADM.ENTNOMBRE) LIKE '%nueva%'
		--AND LOWER(GEENENTADM.ENTNOMBRE) LIKE '%ASMET%'
		--AND (LOWER(GENDETCON.GDENOMBRE) LIKE '%FIDEICOMISO%')

        AND ADNINGRESO.AINFECEGRE IS NOT NULL
)
SELECT
    *
FROM
    CTE
WHERE
    ROW_NUM = 1;