-- CONSULTA RELACIONADA DONDE SE EXTRAEN LAS PACIENTES EXTRANJERAS QUE INGRESAN A URGENCIAS GINECOLOGIA
-- liderginecologia@hospitalsanjose.gov.co

SELECT DISTINCT
	GENPACIEN.PACNUMDOC AS HISTORIA,
	GENPACIEN.PACPRIAPE AS PRIMER_APELLIDO,
	GENPACIEN.PACSEGAPE AS SEGUNDO_APELLIDO,
	GENPACIEN.PACPRINOM as PRIMER_NOMBRE,
	GENPACIEN.PACSEGNOM as SEGUNDO_NOMBRE,
	DATEDIFF(YEAR, GENPACIEN.GPAFECNAC, ADNINGRESO.AINFECING) - CASE WHEN (MONTH(GENPACIEN.GPAFECNAC) > MONTH(ADNINGRESO.AINFECING) OR  (MONTH(GENPACIEN.GPAFECNAC) = MONTH(ADNINGRESO.AINFECING) AND DAY(GENPACIEN.GPAFECNAC) > DAY(ADNINGRESO.AINFECING))) THEN 1 ELSE 0 END AS EDAD,
	CASE WHEN GENPACIEN.GPASEXPAC = 1 THEN 'M' WHEN GENPACIEN.GPASEXPAC = 2 THEN 'F' ELSE NULL END AS GENERO
	, GENPAISES.gpanombre AS PAIS
	, GENESPECI.GEEDESCRI AS ESPECIALIDAD_RESPONSABLE
	, FORMAT(ADNINGRESO.AINFECING, 'yyyy-MM-dd', 'es-CO') AS FECHA_INGRESO
FROM ADNINGRESO
	INNER JOIN HCNFOLIO ON HCNFOLIO.ADNINGRESO = ADNINGRESO.OID
    INNER JOIN GENPACIEN ON HCNFOLIO.GENPACIEN = GENPACIEN.OID
    LEFT JOIN GENDETCON ON GENPACIEN.GENDETCON = GENDETCON.OID
    LEFT JOIN GENARESER on HCNFOLIO.GENARESER =  GENARESER.OID
    LEFT JOIN GENESPECI on HCNFOLIO.GENESPECI = GENESPECI.OID
	LEFT JOIN GENPAISES ON GENPACIEN.GENPAIS = GENPAISES.OID
WHERE
	ADNINGRESO.AINFECING BETWEEN CONVERT(DATETIME, '2025-12-01', 120) AND CONVERT(DATETIME, '2026-01-01', 120)
	AND GENESPECI.GEEDESCRI LIKE 'GINE%' 
	AND GENARESER.GASNOMBRE NOT LIKE '%EXTER%'
	AND GENPAISES.gpanombre NOT LIKE '%Colomb%'
ORDER BY FECHA_INGRESO desc