SELECT DISTINCT
        GENPACIEN.PACNUMDOC AS A_4_Número,
        FORMAT(HCNFOLIO.HCFECFOL, 'yyyy-MM-dd', 'en-us') AS fecha,
        FORMAT(HCMHC67.HCCM05N312, 'yyyy-MM-dd', 'en-us')  as A_33_FPP
    FROM ADNINGRESO
        INNER JOIN HCNFOLIO ON HCNFOLIO.ADNINGRESO = ADNINGRESO.OID
        INNER JOIN GENPACIEN ON HCNFOLIO.GENPACIEN = GENPACIEN.OID
        INNER JOIN HCMHC67 on HCMHC67.HCNFOLIO = HCNFOLIO.OID
    WHERE 
		ADNINGRESO.AINFECING BETWEEN CONVERT(DATETIME, '2025-10-01', 120) AND CONVERT(DATETIME, '2025-10-12', 120)
		
				and GENPACIEN.PACNUMDOC = '1059239171'