SELECT DISTINCT
	GENPACIEN.PACNUMDOC Documento
	, ADNINGRESO.AINCONSEC Ingreso
    , FORMAT(ADNINGRESO.AINFECING, 'yyyy-MM-dd', 'en-us') [Fecha Ingreso]
    , FORMAT(ADNINGRESO.AINFECEGRE, 'yyyy-MM-dd', 'en-us') [Fecha Egreso]
FROM ADNINGRESO
    INNER join GENPACIEN ON ADNINGRESO.GENPACIEN = GENPACIEN.OID
	INNER JOIN HCNFOLIO ON HCNFOLIO.ADNINGRESO = ADNINGRESO.OID
WHERE
GENPACIEN.PACNUMDOC in ()

--AND ADNINGRESO.AINFECING BETWEEN CONVERT(DATETIME, '2026-02-01', 120) AND CONVERT(DATETIME, '2026-03-01', 120)