-- INFORME PARA EXTRAER LA DIFERENCIA ENTRE LA SOLICITUD DE UN EXAMEN HASTA LA RESPUESTA DEL MISMO
-- LABORATORIO CLINICO
-- PERIOCIDAD MENSUAL
SELECT DISTINCT
GENPACIEN.PACNUMDOC AS HISTORIA,
	HCNFOLIO.HCNUMFOL
	, ADNINGRESO.AINCONSEC
	, FORMAT(HCNSOLEXA.HCSFECSOL, 'dd/MM/yyyy HH:mm', 'es-ES') AS [FECHA_SOLICITUD]
	, FORMAT(HCNRESEXA.HCRFECRES, 'dd/MM/yyyy HH:mm', 'es-ES') AS [FECHA_RESULTADO]
	, CASE 
		WHEN HCNSOLEXA.HCSFECSOL IS NULL OR HCNRESEXA.HCRFECRES IS NULL THEN ''
		ELSE ROUND(
			CAST(DATEDIFF_BIG(SECOND, HCNSOLEXA.HCSFECSOL, HCNRESEXA.HCRFECRES) AS FLOAT) / 3600.0, 2)
	END AS HORAS_DIFERENCIA
	, GENSERIPS.SIPCODIGO AS INFORMACION_SERVICIO
	, GENSERIPS.SIPNOMBRE
	, CTNCENCOS.CCCODIGO AS COD_CENCOS_PRES
	, CTNCENCOS.CCNOMBRE AS NOM_CENCOS_PRES
	, Case HCNSOLEXA.HCSESTADO 
		When '0' Then 'Urgente' 
		When '1' Then 'Rutinario'
		When '2' Then 'Electiva' 
		When '3' Then 'Prioritaria'
		When '4' Then 'Muy Urgente' 
		When '5' Then 'Control'
		When '6' Then 'Electivo-Programado' 
		When '-1' Then 'Ninguno'
	End As TIPO_SOLICITUD
	, Case GENSERIPS.SIPGRUPOS 
		When '1' Then 'Diagnostico'
		When '2' Then 'Laboratorio'
		When '3' Then 'Odontologia'
		When '4' Then 'Consulta_Urgencias '
		When '5' Then 'Hospitalizacion' 
	End As AREA
	FROM ADNINGRESO
        INNER JOIN HCNFOLIO ON HCNFOLIO.ADNINGRESO = ADNINGRESO.OID
        LEFT JOIN GENPACIEN ON HCNFOLIO.GENPACIEN = GENPACIEN.OID
		LEFT JOIN HCNSOLEXA ON HCNFOLIO.OID = HCNSOLEXA.HCNFOLIO
		LEFT JOIN HCNRESEXA ON HCNSOLEXA.OID = HCNRESEXA.HCNSOLEXA
        LEFT JOIN GENSERIPS ON GENSERIPS.OID = HCNSOLEXA.GENSERIPS
        LEFT JOIN GENARESER on HCNFOLIO.GENARESER =  GENARESER.OID
        LEFT JOIN CTNCENCOS on GENARESER.CTNCENCOS1 =  CTNCENCOS.OID
     WHERE
		HCNSOLEXA.HCSFECSOL Between CONVERT(DATETIME, '2025-12-01', 120) AND CONVERT(DATETIME, '2026-01-01', 120)
		AND GENSERIPS.SIPGRUPOS  = 2
	ORDER BY FECHA_SOLICITUD DESC