SET DATEFORMAT ymd;
DECLARE @FechaInicio DATETIME;
DECLARE @FechaFinal DATETIME;

SET @FechaInicio = '2026-01-27 00:00:00';
SET @FechaFinal = '2026-01-27 23:59:59';

-- NOTAS OPERATORIAS --

WITH DatosFiltrados AS (
    SELECT
        GENPACIEN.PACNUMDOC AS HISTORIA,
        CASE
            GENPACIEN.PACTIPDOC
            WHEN 1 THEN 'CC'
            WHEN 2 THEN 'CE'
            WHEN 3 THEN 'TI'
            WHEN 4 THEN 'RC'
            WHEN 5 THEN 'PA'
            WHEN 6 THEN 'AS'
            WHEN 7 THEN 'MS'
            WHEN 8 THEN 'NU'
            WHEN 10 THEN 'CN'
            WHEN 12 THEN 'PE'
            WHEN 14 THEN 'PE'
            WHEN 15 THEN 'PE'
            WHEN 9 THEN 'PE'
            ELSE 'NONE'
        END AS TIPO_DOC,
        GENPACIEN.GPANOMCOM AS NOMBRES,
        FORMAT(HCFECFOL, 'yyyy-MM-dd hh:mm', 'es-ES') AS FECHA_HC,
        ADNINGRESO.AINCONSEC as INGRESO,
        CASE
            WHEN GENPACIEN.GPASEXPAC = 1 THEN 'M'
            WHEN GENPACIEN.GPASEXPAC = 2 THEN 'F'
            ELSE NULL
        END AS SEXO,
        DATEDIFF(YEAR, GENPACIEN.GPAFECNAC, ADNINGRESO.AINFECING) - CASE
            WHEN (
                MONTH(GENPACIEN.GPAFECNAC) > MONTH(ADNINGRESO.AINFECING)
                OR (
                    MONTH(GENPACIEN.GPAFECNAC) = MONTH(ADNINGRESO.AINFECING)
                    AND DAY(GENPACIEN.GPAFECNAC) > DAY(ADNINGRESO.AINFECING)
                )
            ) THEN 1
            ELSE 0
        END AS EDAD,
        FORMAT(GENPACIEN.GPAFECNAC, 'yyyy-MM-dd', 'es-ES') AS FECHA_NAC,
        GENSERIPS.SIPCODCUP AS CODCUPS,
        GENSERIPS.SIPDESCUP AS DESCRIPCIONCUPS,
        HCNTIPHIS.HCCODIGO,
        HCNTIPHIS.HCNOMBRE,
        GENARESER.GASCODIGO,
        GENARESER.GASNOMBRE,
        GENMEDICO.GMENOMCOM AS MEDICO,
        GENESPECI.GEEDESCRI,
        GENDIAGNO.DIACODIGO,
        GENDIAGNO.DIANOMBRE AS DIAGNOSTICO,
        GENDETCON.GDENOMBRE AS ENTIDAD,
        ROW_NUMBER() OVER (PARTITION BY GENPACIEN.PACNUMDOC ORDER BY HCFECFOL DESC) AS RN
    FROM
        ADNINGRESO
        INNER JOIN HCNFOLIO ON HCNFOLIO.ADNINGRESO = ADNINGRESO.OID
        INNER JOIN GENPACIEN ON HCNFOLIO.GENPACIEN = GENPACIEN.OID
        INNER JOIN HCNTIPHIS ON HCNFOLIO.HCNTIPHIS = HCNTIPHIS.OID
        INNER JOIN HCNQXEPAC ON HCNQXEPAC.HCNFOLIO = HCNFOLIO.oid
        INNER JOIN GENSERIPS ON HCNQXEPAC.GENSERIPS = GENSERIPS.OID
        INNER JOIN GENARESER ON HCNFOLIO.GENARESER = GENARESER.OID
        INNER JOIN GENMEDICO ON HCNFOLIO.GENMEDICO = GENMEDICO.OID
        INNER JOIN GENESPECI ON HCNFOLIO.GENESPECI = GENESPECI.OID
        INNER JOIN HCNDIAPAC ON HCNFOLIO.OID = HCNDIAPAC.HCNFOLIO
        INNER JOIN GENDIAGNO ON GENDIAGNO.OID = HCNDIAPAC.GENDIAGNO
        INNER JOIN GENDETCON ON GENPACIEN.GENDETCON = GENDETCON.OID
    WHERE
        HCFECFOL BETWEEN @FechaInicio AND @FechaFinal
        AND (
            LOWER(GENDIAGNO.DIACODIGO) LIKE '%c%'
            OR LOWER(GENDIAGNO.DIACODIGO) LIKE '%d%'
        )
		AND (LOWER(GENDETCON.GDENOMBRE) LIKE '%NUEVA%')
)

SELECT *
FROM DatosFiltrados
WHERE RN = 1
OPTION (RECOMPILE);


-- QUIMIOS - SALA ADMINISTRACI”N MEDICAMENTOS ESPECIALES
    SELECT 
        GENPACIEN.PACNUMDOC AS HISTORIA,
        FORMAT(GENPACIEN.GPAFECNAC, 'yyyy-MM-dd', 'es-ES') AS FECHA_NAC,
        CASE WHEN GENPACIEN.GPASEXPAC = 1 THEN 'M' WHEN GENPACIEN.GPASEXPAC = 2 THEN 'F' ELSE NULL END AS SEXO,
        CASE WHEN TRIM(GENPACIEN.PACPRIAPE) = '' THEN 'NONE'
             ELSE REPLACE(TRANSLATE(TRIM(GENPACIEN.PACPRIAPE), '·ÈÌÛ˙¡…Õ”⁄Ò—', 'aeiouAEIOUNN'), ' ', '')
        END AS PRIMER_APELLIDO,
        CASE WHEN TRIM(GENPACIEN.PACSEGAPE) = '' THEN 'NONE'
             ELSE REPLACE(TRANSLATE(TRIM(GENPACIEN.PACSEGAPE), '·ÈÌÛ˙¡…Õ”⁄Ò—', 'aeiouAEIOUNN'), ' ', '')
        END AS SEGUNDO_APELLIDO,
        CASE WHEN TRIM(GENPACIEN.PACPRINOM) = '' THEN 'NONE'
             ELSE REPLACE(TRANSLATE(TRIM(GENPACIEN.PACPRINOM), '·ÈÌÛ˙¡…Õ”⁄Ò—', 'aeiouAEIOUNN'), ' ', '')
        END AS PRIMER_NOMBRE,
        CASE WHEN TRIM(GENPACIEN.PACSEGNOM) = '' THEN 'NONE'
             ELSE REPLACE(TRANSLATE(TRIM(GENPACIEN.PACSEGNOM), '·ÈÌÛ˙¡…Õ”⁄Ò—', 'aeiouAEIOUNN'), ' ', '')
        END AS SEGUNDO_NOMBRE,
        FORMAT(HCMHC48.HCCM05N05, 'yyyy-MM-dd hh:mm', 'es-ES') AS FECHA,
        GENDIAGNO.DIACODIGO AS CIE10,
        GENDIAGNO.DIANOMBRE AS DX,
        HCMHC48.HCCM01N03 AS NRO_CICLOS,
        HCMHC48.HCCM04N04 AS ESQUEMA,
        GENTERCER.TERNOMCOM AS EAPB,
		HCNTIPHIS.HCCODIGO AS COD_SUBAREA, HCNTIPHIS.HCNOMBRE AS NOMBRE_SUBAREA,
		GENARESER.GASCODIGO AS COD_AREA, GENARESER.GASNOMBRE AS AREA,

        CASE WHEN GENDETCON.GDEPOSSUB = 1 THEN 'SUBSIDIADO' 
             WHEN GENDETCON.GDEPOSSUB = 0 THEN 'CONTRIBUTIVO' ELSE '' 
        END AS REG_EAPB,
        ROW_NUMBER() OVER (PARTITION BY GENPACIEN.PACNUMDOC ORDER BY HCMHC48.HCCM05N05 DESC) AS RN
    FROM 
        ADNINGRESO
        INNER JOIN HCNFOLIO ON HCNFOLIO.ADNINGRESO = ADNINGRESO.OID
        INNER JOIN GENPACIEN ON HCNFOLIO.GENPACIEN = GENPACIEN.OID
        LEFT JOIN GENDETCON ON GENPACIEN.GENDETCON = GENDETCON.OID
        LEFT JOIN GENTERCER ON GENDETCON.GENTERCER1 = GENTERCER.OID
        INNER JOIN HCMHC48 ON HCMHC48.HCNFOLIO = HCNFOLIO.OID
        INNER JOIN HCNDIAPAC ON HCNFOLIO.OID = HCNDIAPAC.HCNFOLIO
        INNER JOIN GENDIAGNO ON GENDIAGNO.OID = HCNDIAPAC.GENDIAGNO

		LEFT JOIN GENARESER on HCNFOLIO.GENARESER =  GENARESER.OID
		LEFT JOIN HCNTIPHIS on HCNFOLIO.HCNTIPHIS = HCNTIPHIS.OID

    WHERE 
        HCNFOLIO.HCFECFOL BETWEEN @FechaInicio AND @FechaFinal
		--AND GENARESER.GASCODIGO != '7356-4'
		AND (
            LOWER(GENDIAGNO.DIACODIGO) LIKE '%c%'
            OR LOWER(GENDIAGNO.DIACODIGO) LIKE '%d%'
        )
		AND (LOWER(GENTERCER.TERNOMCOM) LIKE '%NUEVA%')
		OPTION (RECOMPILE);


-- EGRESOS

WITH CTE AS (
    SELECT
        GENPACIEN.PACNUMDOC AS HISTORIA,
        GENPACIEN.GPANOMCOM AS NOMBRES,
        FORMAT(GENPACIEN.GPAFECNAC, 'yyyy-MM-dd', 'es-ES') AS FECHA_NAC,
        CASE
            WHEN GENPACIEN.GPASEXPAC = 1 THEN 'M'
            WHEN GENPACIEN.GPASEXPAC = 2 THEN 'F'
            ELSE NULL
        END AS SEXO,
        FORMAT(HCFECFOL, 'yyyy-MM-dd hh:mm', 'es-ES') AS FECHA_FOLIO,
        FORMAT(
            ADNINGRESO.AINFECING,
            'yyyy-MM-dd hh:mm',
            'es-ES'
        ) AS FECHA_INGRESO,
        CASE
            WHEN GENARESER.GASCODIGO = '7311'
            AND ISDATE(ADNINGRESO.AINFECING) = 1 THEN FORMAT(
                CAST(ADNINGRESO.AINFECING AS DATETIME),
                'yyyy-MM-dd HH:mm',
                'es-ES'
            )
            WHEN GENARESER.GASCODIGO = '7311-1'
            AND ISDATE(ADNINGRESO.AINFECING) = 1 THEN FORMAT(
                CAST(ADNINGRESO.AINFECING AS DATETIME),
                'yyyy-MM-dd HH:mm',
                'es-ES'
            )
            WHEN GENARESER.GASCODIGO = '7354-2'
            AND ISDATE(ADNINGRESO.AINFECING) = 1 THEN FORMAT(
                CAST(ADNINGRESO.AINFECING AS DATETIME),
                'yyyy-MM-dd HH:mm',
                'es-ES'
            )
            WHEN ISDATE(ADNINGRESO.AINFECEGRE) = 1 THEN FORMAT(
                CAST(ADNINGRESO.AINFECEGRE AS DATETIME),
                'yyyy-MM-dd HH:mm',
                'es-ES'
            )
            ELSE NULL -- O alguna fecha por defecto si es necesario
        END AS FECHA_EGRESO,
        GENDIAGNO.DIACODIGO AS DX,
        GENDIAGNO.DIANOMBRE AS DIAGNOSTICO,
        HCNTIPHIS.HCCODIGO,
        HCNTIPHIS.HCNOMBRE,
        HCNDIAPAC.HCPDIAPRIN,
        GENMEDICO.GMENOMCOM AS MEDICO,
        GENESPECI.GEEDESCRI,
        GENARESER.GASNOMBRE,
        
		--GENTERCER.TERNOMCOM AS ENTIDAD,
        --CASE
        --    WHEN GENDETCON.GDEPOSSUB = 1 THEN 'SUBSIDIADO'
        --    WHEN GENDETCON.GDEPOSSUB = 0 THEN 'CONTRIBUTIVO'
        --    ELSE ''
        --END AS REGIMEN,

		GEENENTADM.ENTCODIGO AS AF_COD_EAPB, GEENENTADM.ENTNOMBRE AS AF_ENTIDAD,

        ADNINGRESO.AINCONSEC AS INGRESO,
        ROW_NUMBER() OVER (
            PARTITION BY GENPACIEN.PACNUMDOC
            ORDER BY
                ADNINGRESO.AINFECING DESC
        ) AS ROW_NUM
    FROM
        ADNINGRESO
        INNER JOIN HCNFOLIO ON HCNFOLIO.ADNINGRESO = ADNINGRESO.OID
        LEFT JOIN GENPACIEN ON HCNFOLIO.GENPACIEN = GENPACIEN.OID
        INNER JOIN HCNTIPHIS ON HCNFOLIO.HCNTIPHIS = HCNTIPHIS.OID
        INNER JOIN HCNDIAPAC ON HCNFOLIO.OID = HCNDIAPAC.HCNFOLIO
        INNER JOIN GENDIAGNO ON GENDIAGNO.OID = HCNDIAPAC.GENDIAGNO
        LEFT JOIN GENDETCON ON GENPACIEN.GENDETCON = GENDETCON.OID
        INNER JOIN GENMEDICO ON HCNFOLIO.GENMEDICO = GENMEDICO.OID
        INNER JOIN GENESPECI ON HCNFOLIO.GENESPECI = GENESPECI.OID
        LEFT JOIN GENARESER ON HCNFOLIO.GENARESER = GENARESER.OID
        LEFT JOIN GENTERCER ON GENDETCON.GENTERCER1 = GENTERCER.OID

		LEFT JOIN GENCONTRA ON GENCONTRA.OID = GENDETCON.GENCONTRA1 
		LEFT JOIN GEENENTADM ON GENCONTRA.DGNENTADM1 = GEENENTADM.OID
    WHERE
        HCFECFOL BETWEEN @FechaInicio
        AND @FechaFinal
        AND (
            LOWER(GENDIAGNO.DIACODIGO) LIKE '%C%'
            OR LOWER(GENDIAGNO.DIACODIGO) LIKE '%D%'
        )
		AND LOWER(GEENENTADM.ENTNOMBRE) LIKE '%NUEVA%'

        AND ADNINGRESO.AINFECEGRE IS NOT NULL
)
SELECT
    *
FROM
    CTE
WHERE
††††ROW_NUM†=†1
OPTION (RECOMPILE);


-- CONSULTAS

WITH ConsultasUnicas AS (
    SELECT
        GENPACIEN.PACNUMDOC AS HISTORIA,
        CONVERT(VARCHAR, CONVERT(DATE, GENPACIEN.GPAFECNAC), 120) AS FECHA_NACIMIENTO,

        GENPACIEN.PACPRINOM + ' ' + 
        ISNULL(GENPACIEN.PACSEGNOM + ' ', '') + 
        GENPACIEN.PACPRIAPE + ' ' + 
        ISNULL(GENPACIEN.PACSEGAPE, '') AS NOMBRE_COMPLETO,

        GENDIAGNO.DIACODIGO AS DX,
        CASE 
            WHEN HCNDIAPAC.HCPDIAPRIN = 1 THEN 'PRINCIPAL' 
            WHEN HCNDIAPAC.HCPDIAPRIN = 0 THEN 'SECUNDARIO' 
            ELSE 'OTRO' 
        END AS TIPO_DX,
        GENDIAGNO.DIANOMBRE AS DIAGNOSTICO,
        GENSERIPS.SIPNOMBRE AS PROCEDIMIENTO,
        GENMEDICO1.GMENOMCOM AS MEDICO,
        GENESPECI1.GEEDESCRI AS ESPECIALIDAD,

        CONVERT(VARCHAR, HCNFOLIO.HCFECFOL, 120) AS FECHA_FOLIO_HC,
        HCNFOLIO.OID AS FOLIO,
        CONVERT(VARCHAR, SLNFACTUR.SFAFECFAC, 120) AS FECHA_FACTURACION,
        SLNFACTUR.SFANUMFAC AS NUMERO_FACTURA,
        CONVERT(VARCHAR, SLNSERPRO.SERFECSER, 120) AS FECHA_SERVICIO,
        CONVERT(VARCHAR, ADNINGRESO.AINFECING, 120) AS FECHA_INGRESO,
        ADNINGRESO.AINCONSEC AS CONSECUTIVO_INGRESO,
        GENDETCON.GDENOMBRE AS ENTIDAD,

        ROW_NUMBER() OVER (
            PARTITION BY GENPACIEN.PACNUMDOC
            ORDER BY HCNFOLIO.HCFECFOL DESC
        ) AS RN
    FROM HCNFOLIO
    INNER JOIN GENMEDICO ON GENMEDICO.OID = HCNFOLIO.GENMEDICO
    INNER JOIN GENPACIEN ON GENPACIEN.OID = HCNFOLIO.GENPACIEN
    INNER JOIN SLNFACTUR ON HCNFOLIO.ADNINGRESO = SLNFACTUR.ADNINGRESO
    INNER JOIN ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO AND ADNINGRESO.GENPACIEN = HCNFOLIO.GENPACIEN
    INNER JOIN SLNSERPRO ON SLNFACTUR.ADNINGRESO = SLNSERPRO.ADNINGRES1
    INNER JOIN GENMEDICO GENMEDICO1 ON GENMEDICO1.OID = SLNSERPRO.GENMEDICO1
    INNER JOIN GENESPECI GENESPECI1 ON GENESPECI1.OID = SLNSERPRO.DGNESPECI1
    INNER JOIN SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
    INNER JOIN SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1 AND SLNORDSER.SOSESTADO = 1
    INNER JOIN GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1 AND GENSERIPS.SIPNOMBRE LIKE '%CONSU%'
    INNER JOIN GENESPECI ON HCNFOLIO.GENESPECI = GENESPECI.OID
    INNER JOIN GENMUNICI ON GENMUNICI.OID = GENPACIEN.DGNMUNICIPIO
    INNER JOIN GENDEPTO ON GENDEPTO.OID = GENMUNICI.GENDEPTO
    INNER JOIN GENDETCON ON SLNFACTUR.GENDETCON = GENDETCON.OID
    INNER JOIN TIPOPLANBENEFICIOS ON TIPOPLANBENEFICIOS.ID = GENDETCON.GDECONFAC
    INNER JOIN HCNDIAPAC ON HCNFOLIO.OID = HCNDIAPAC.HCNFOLIO
    INNER JOIN GENDIAGNO ON GENDIAGNO.OID = HCNDIAPAC.GENDIAGNO
    WHERE 
        HCNFOLIO.HCFECFOL BETWEEN @FechaInicio AND @FechaFinal
        AND (LOWER(GENDIAGNO.DIACODIGO) LIKE '%c%' OR LOWER(GENDIAGNO.DIACODIGO) LIKE '%d%')
		AND (LOWER(GENDETCON.GDENOMBRE) LIKE '%NUEVA%')
)

SELECT *
FROM ConsultasUnicas
WHERE RN = 1
OPTION (RECOMPILE);