-- OFTALMOLOGIA
SELECT DISTINCT
   
    CASE
        GENPACIEN.PACTIPDOC
        WHEN 1 THEN 'CC'
        WHEN 2 THEN 'CE'
        WHEN 3 THEN 'TI'
        WHEN 4 THEN 'RC'
        WHEN 5 THEN 'PA'
        WHEN 6 THEN 'AS'
        WHEN 7 THEN 'MS'
        WHEN 8 THEN 'NU'
        WHEN 10 THEN 'CN'
        WHEN 12 THEN 'PE'
        WHEN 14 THEN 'PE'
        WHEN 15 THEN 'PE'
        WHEN 9 THEN 'PE'
        ELSE 'NONE'
    END AS TIPO_DOC,
    GENPACIEN.PACNUMDOC AS HISTORIA,
    GENPACIEN.PACPRIAPE AS PRIMER_APELLIDO,
    CASE
        WHEN GENPACIEN.PACSEGAPE = '' THEN 'NONE'
        ELSE GENPACIEN.PACSEGAPE
    END AS SEGUNDO_APELLIDO,
    GENPACIEN.PACPRINOM AS PRIMER_NOMBRE,
    CASE
        WHEN GENPACIEN.PACSEGNOM = '' THEN 'NONE'
        ELSE GENPACIEN.PACSEGNOM
    END AS SEGUNDO_NOMBRE,
     
    FORMAT(GENPACIEN.GPAFECNAC, 'yyyy-MM-dd', 'es-ES') AS FECHA_NAC,
	-- Fecha de corte para calcular la edad mayor a 3 años
	DATEDIFF(YEAR, GENPACIEN.GPAFECNAC, '2024-12-31') - CASE
        WHEN (
            MONTH(GENPACIEN.GPAFECNAC) > MONTH('2024-12-31')
            OR (
                MONTH(GENPACIEN.GPAFECNAC) = MONTH('2024-12-31')
                AND DAY(GENPACIEN.GPAFECNAC) > DAY('2024-12-31')
            )
        ) THEN 1
        ELSE 0
    END AS EDAD,
    CASE
        WHEN GENPACIEN.GPASEXPAC = 1 THEN 'M'
        WHEN GENPACIEN.GPASEXPAC = 2 THEN 'F'
        ELSE NULL
    END AS SEXO,
    ADNGRUETN.ADGGRUETN AS ETNIA,
    ADNGRUETN.ADGENOMBRE AS NOMBRE_ETNIA,
    TRY_CAST(ADNINGRESO.ADINFPACI AS XML).value(
        '(/HCCLInfoPaciente/@NOMOCUPA)[1]',
        'VARCHAR(255)'
    ) AS OCUPACION,
    GENCARGO.GCANOMBRE AS NIVEL_EDUCATIVO,
    FORMAT(HCFECFOL, 'yyyy-MM-dd', 'en-us') AS FECHA_ATENCION,
    HCMHC35.HCCM02N04 AS OD1,
    HCMHC35.HCCM02N05 AS OD2,
    HCMHC35.HCCM02N06 AS OI1,
    HCMHC35.HCCM02N07 AS OI2,
    HCNTIPHIS.HCNOMBRE AS PROCEDIMIENTO,
    ADNINGRESO.AINCONSEC AS INGRESO
FROM
    ADNINGRESO
    LEFT JOIN HCNFOLIO ON HCNFOLIO.ADNINGRESO = ADNINGRESO.OID
    LEFT JOIN GENPACIEN ON HCNFOLIO.GENPACIEN = GENPACIEN.OID
    LEFT JOIN ADNGRUETN ON GENPACIEN.ADNGRUETN = ADNGRUETN.ADGGRUETN
    INNER JOIN HCNTIPHIS ON HCNFOLIO.HCNTIPHIS = HCNTIPHIS.OID
    INNER JOIN HCMHC35 ON HCMHC35.HCNFOLIO = HCNFOLIO.OID
    LEFT JOIN GENCARGO ON GENPACIEN.GENCARGO1 = GENCARGO.OID
WHERE
    HCFECFOL BETWEEN CONVERT(DATETIME, '2024-12-27 00:00', 120)
    AND CONVERT(DATETIME, '2025-01-01 00:00', 120)
    AND (
        DATEDIFF(YEAR, GENPACIEN.GPAFECNAC, '2024-12-31') - CASE
            WHEN (
                MONTH(GENPACIEN.GPAFECNAC) > MONTH('2024-12-31')
                OR (
                    MONTH(GENPACIEN.GPAFECNAC) = MONTH('2024-12-31')
                    AND DAY(GENPACIEN.GPAFECNAC) > DAY('2024-12-31')
                )
            ) THEN 1
            ELSE 0
        END
    ) > 3;