-- NOTAS OPERATORIAS --

WITH DatosFiltrados AS (
    SELECT
        GENPACIEN.PACNUMDOC AS HISTORIA,
        CASE
            GENPACIEN.PACTIPDOC
            WHEN 1 THEN 'CC'
            WHEN 2 THEN 'CE'
            WHEN 3 THEN 'TI'
            WHEN 4 THEN 'RC'
            WHEN 5 THEN 'PA'
            WHEN 6 THEN 'AS'
            WHEN 7 THEN 'MS'
            WHEN 8 THEN 'NU'
            WHEN 10 THEN 'CN'
            WHEN 12 THEN 'PE'
            WHEN 14 THEN 'PE'
            WHEN 15 THEN 'PE'
            WHEN 9 THEN 'PE'
            ELSE 'NONE'
        END AS TIPO_DOC,
        GENPACIEN.GPANOMCOM AS NOMBRES,
        FORMAT(HCFECFOL, 'yyyy-MM-dd hh:mm', 'en-us') AS FECHA_HC,
        ADNINGRESO.AINCONSEC as INGRESO,
        CASE
            WHEN GENPACIEN.GPASEXPAC = 1 THEN 'M'
            WHEN GENPACIEN.GPASEXPAC = 2 THEN 'F'
            ELSE NULL
        END AS SEXO,
        DATEDIFF(YEAR, GENPACIEN.GPAFECNAC, ADNINGRESO.AINFECING) - CASE
            WHEN (
                MONTH(GENPACIEN.GPAFECNAC) > MONTH(ADNINGRESO.AINFECING)
                OR (
                    MONTH(GENPACIEN.GPAFECNAC) = MONTH(ADNINGRESO.AINFECING)
                    AND DAY(GENPACIEN.GPAFECNAC) > DAY(ADNINGRESO.AINFECING)
                )
            ) THEN 1
            ELSE 0
        END AS EDAD,
        FORMAT(GENPACIEN.GPAFECNAC, 'yyyy-MM-dd', 'en-us') AS FECHA_NAC,
        GENSERIPS.SIPCODCUP AS CODCUPS,
        GENSERIPS.SIPDESCUP AS DESCRIPCIONCUPS,
        HCNTIPHIS.HCCODIGO,
        HCNTIPHIS.HCNOMBRE,
        GENARESER.GASCODIGO,
        GENARESER.GASNOMBRE,
        GENMEDICO.GMENOMCOM AS MEDICO,
        GENESPECI.GEEDESCRI,
        GENDIAGNO.DIACODIGO,
        GENDIAGNO.DIANOMBRE AS DIAGNOSTICO,
        GENDETCON.GDENOMBRE AS ENTIDAD,
        ROW_NUMBER() OVER (PARTITION BY GENPACIEN.PACNUMDOC ORDER BY HCFECFOL DESC) AS RN
    FROM
        ADNINGRESO
        INNER JOIN HCNFOLIO ON HCNFOLIO.ADNINGRESO = ADNINGRESO.OID
        INNER JOIN GENPACIEN ON HCNFOLIO.GENPACIEN = GENPACIEN.OID
        INNER JOIN HCNTIPHIS ON HCNFOLIO.HCNTIPHIS = HCNTIPHIS.OID
        INNER JOIN HCNQXEPAC ON HCNQXEPAC.HCNFOLIO = HCNFOLIO.oid
        INNER JOIN GENSERIPS ON HCNQXEPAC.GENSERIPS = GENSERIPS.OID
        INNER JOIN GENARESER ON HCNFOLIO.GENARESER = GENARESER.OID
        INNER JOIN GENMEDICO ON HCNFOLIO.GENMEDICO = GENMEDICO.OID
        INNER JOIN GENESPECI ON HCNFOLIO.GENESPECI = GENESPECI.OID
        INNER JOIN HCNDIAPAC ON HCNFOLIO.OID = HCNDIAPAC.HCNFOLIO
        INNER JOIN GENDIAGNO ON GENDIAGNO.OID = HCNDIAPAC.GENDIAGNO
        INNER JOIN GENDETCON ON GENPACIEN.GENDETCON = GENDETCON.OID
    WHERE
        HCFECFOL BETWEEN CONVERT(DATETIME, '2025-10-29 00:00:00', 120) AND CONVERT(DATETIME, '2025-10-30 00:00:00', 120)
        AND (
            LOWER(GENDIAGNO.DIACODIGO) LIKE '%c%'
            OR LOWER(GENDIAGNO.DIACODIGO) LIKE '%d%'
        )
        AND (LOWER(GENDETCON.GDENOMBRE) LIKE '%NUEVA%')
)

SELECT *
FROM DatosFiltrados
WHERE RN = 1;