-- CONSULTA DEPREECLAMSIA - ELIMINACIÓN DE DUPLICADOS CON PRIORIDAD EN PRINCIPAL
-- URGENCIAS GINECOLOGIA

WITH IngresosFiltrados AS (
    SELECT DISTINCT *
    FROM ADNINGRESO
    WHERE AINFECING >= CONVERT(datetime, '2025-10-01 00:00:00', 120) 
      AND AINFECING < CONVERT(datetime, '2025-10-31 23:59:59', 120)
      AND AINFECEGRE IS NOT NULL
),
DatosNumerados AS (
    SELECT 
        ING.AINCONSEC AS INGRESO
        , GENPACIEN.PACNUMDOC AS [HISTORIA]
        , GENPACIEN.GPANOMCOM AS NOMBRES
        , DATEDIFF(YEAR, GENPACIEN.GPAFECNAC, ING.AINFECING)
            - CASE WHEN (MONTH(GENPACIEN.GPAFECNAC) > MONTH(ING.AINFECING)
            OR (MONTH(GENPACIEN.GPAFECNAC) = MONTH(ING.AINFECING) AND DAY(GENPACIEN.GPAFECNAC) > DAY(ING.AINFECING)))
            THEN 1 ELSE 0 END AS EDAD
        , CASE WHEN GENPACIEN.GPASEXPAC = 1 THEN 'MASCULINO' WHEN GENPACIEN.GPASEXPAC = 2 THEN 'FEMENINO' ELSE NULL END AS GENERO
        , GENDIAGNO.DIACODIGO AS COD_DAT
        , GENDIAGNO.DIANOMBRE AS NAM_DAT
        , CASE WHEN HCNDIAPAC.HCPDIAPRIN = 1 THEN 'PRINCIPAL' WHEN HCNDIAPAC.HCPDIAPRIN = 0 THEN 'SEC' ELSE '' END AS TIP_COD_DAT
        , FORMAT(ING.AINFECING, 'yyyy-MM-dd H:mm') AS [FECHA_INGRESO]
        , FORMAT(ING.AINFECEGRE, 'yyyy-MM-dd H:mm') AS [FECHA_EGRESO]
        , DAIN.DIACODIGO AS [COD DX INGRESO]
        , DAIN.DIANOMBRE AS [DIAGNOSTICO INGRESO]
        , DA.DIACODIGO AS [COD DX EGRESO]
        , DA.DIANOMBRE AS [DIAGNOSTICO EGRESO]
        
        -- Lógica de partición corregida:
        , ROW_NUMBER() OVER (
            PARTITION BY 
                GENPACIEN.PACNUMDOC,    -- Misma Historia
                GENDIAGNO.DIACODIGO,    -- Mismo COD_DAT
                ING.AINFECING,          -- Misma FECHA_INGRESO
                ING.AINFECEGRE,          -- Misma FECHA_EGRESO
                DAIN.DIACODIGO,         -- Mismo COD DX INGRESO
                DA.DIACODIGO            -- Mismo COD DX EGRESO
            ORDER BY HCNDIAPAC.HCPDIAPRIN DESC -- Prioriza 1 (PRINCIPAL) sobre 0 (SEC)
          ) AS RN
    FROM IngresosFiltrados ING
        INNER JOIN HCNFOLIO ON HCNFOLIO.ADNINGRESO = ING.OID
        INNER JOIN GENPACIEN ON HCNFOLIO.GENPACIEN = GENPACIEN.OID
        INNER JOIN HCNDIAPAC ON HCNFOLIO.OID = HCNDIAPAC.HCNFOLIO
        INNER JOIN GENDIAGNO ON GENDIAGNO.OID = HCNDIAPAC.GENDIAGNO
        AND GENDIAGNO.DIACODIGO IN ('O722','O11X','O140','O141','O150','O151','O152')

    OUTER APPLY (
        SELECT TOP (1) g.DIACODIGO, g.DIANOMBRE
        FROM primer_folio pf
            JOIN HCNFOLIO hf2 ON hf2.OID = pf.folio
            JOIN HCNDIAPAC h2 ON h2.HCNFOLIO = hf2.OID
            JOIN GENDIAGNO g ON g.OID = h2.GENDIAGNO
        WHERE pf.oidingreso = ING.oid
    ) DAIN

    OUTER APPLY (
        SELECT TOP (1) g.DIACODIGO, g.DIANOMBRE
        FROM ADNEGRESO ae
            JOIN ADNDIAEGR de ON de.ADNEGRESO = ae.OID
            JOIN GENDIAGNO g ON g.OID = de.DIACODIGO
        WHERE ae.OID = ING.ADNEGRESO
    ) DA
)
SELECT 
    INGRESO, HISTORIA, NOMBRES, EDAD, GENERO, COD_DAT, NAM_DAT, 
    TIP_COD_DAT, FECHA_INGRESO, FECHA_EGRESO, [COD DX INGRESO], 
    [DIAGNOSTICO INGRESO], [COD DX EGRESO], [DIAGNOSTICO EGRESO]
FROM DatosNumerados
WHERE RN = 1
ORDER BY FECHA_INGRESO DESC;