CREATE TABLE res0247
(
    _1_primernombre VARCHAR(50) NOT NULL,
    _2_segundonombre VARCHAR(50) NOT NULL DEFAULT 'NONE',
    _3_primerapellido VARCHAR(50) NOT NULL,
    _4_segundoapellido VARCHAR(50) NOT NULL DEFAULT 'NOAP',
    _5_tipoidentificacion CHAR(2) NOT NULL,
    _6_identificacion VARCHAR(20) NOT NULL,
    _7_fechanac DATE NOT NULL,
    _8_sexo CHAR(1) NOT NULL CHECK (_8_sexo IN ('F','M')),
    _9_codocupacion CHAR(4) NOT NULL CHECK (_9_codocupacion LIKE '[0-9][0-9][0-9][0-9]'),
    _10_regimen CHAR(1) NOT NULL,
    _11_eps VARCHAR(10) NOT NULL,
    _12_codetnia TINYINT NOT NULL CHECK (_12_codetnia BETWEEN 1 AND 6),
    _13_grupopob SMALLINT NOT NULL,
    _14_codigomunicipio CHAR(5) NOT NULL,
    _15_telefono VARCHAR(50) NOT NULL,
    _16_fechaafileps DATE NOT NULL,
    _17_dxcie10ca VARCHAR(10) NULL,
    _18_fechadxca DATE NOT NULL,
    _19_fecharem DATE NOT NULL,
    _20_fechaingipsdx DATE NOT NULL,
    _21_tipestudio TINYINT NULL,
    _22_motivonodxhispatologico TINYINT NULL,
    _23_fechaesthispatologico DATE NULL,
    _24_fechainfhispat DATE NULL,
    _25_codipsconfdx CHAR(12) NOT NULL,
    _26_fecha1csmed DATE NOT NULL,
    _27_histologiatumor TINYINT NOT NULL,
    _28_gdodiftumor TINYINT NOT NULL,
    _29_estadiotnm VARCHAR(20) NOT NULL,
    _30_fechaesttnm DATE NOT NULL,
    _31_pbaher2camama TINYINT NOT NULL,
    _32_fechaher2 DATE NOT NULL,
    _33_resulher2 TINYINT NOT NULL,
    _34_estdukescacolorectal TINYINT NOT NULL,
    _35_fechaestdukes DATE NOT NULL,
    _36_estlinfomanohodgkin TINYINT NOT NULL,
    _37_clgleasoncaprostata TINYINT NOT NULL,
    _38_clriesgoleucemia TINYINT NOT NULL,
    _39_fechaclriesgo DATE NOT NULL,
    _40_obtramtomedinicial TINYINT NOT NULL,
    _41_obtramtointervencionmed TINYINT NOT NULL,
    _42_antotroca1ario TINYINT NOT NULL,
    _43_fechaotroca1ario DATE NOT NULL,
    _44_tipocie10caantecedente VARCHAR(10) NOT NULL,
    _45_requimiotesist TINYINT NOT NULL,
    _46_fasesquimiopro TINYINT NOT NULL,
    _46_1_requimioprefase TINYINT NOT NULL,
    _46_2_requimioinduccion TINYINT NOT NULL,
    _46_3_requimiointensificacion TINYINT NOT NULL,
    _46_4_requimioconsolidacion TINYINT NOT NULL,
    _46_5_requimioreinduccion TINYINT NOT NULL,
    _46_6_requimiomantenimiento TINYINT NOT NULL,
    _46_7_requimiomantenimientolargo TINYINT NOT NULL,
    _46_8_requimiootra TINYINT NOT NULL,
    _47_nociclosiniciados TINYINT NOT NULL,
    _48_ubitmp1erciclooncologico TINYINT NOT NULL,
    _49_fechaini1ercloquimio DATE NOT NULL,
    _50_noipssuministran1erciclo TINYINT NOT NULL,
    _51_codips1suministran1erciclo CHAR(12) NOT NULL,
    _52_codips2suministran1erciclo CHAR(12) NOT NULL,
    _53_ctosmedantineoplasticos1erciclo TINYINT NOT NULL,
    _53_1_medicamentoadm1 VARCHAR(20) NOT NULL,
    _53_2_medicamentoadm2 VARCHAR(20) NOT NULL,
    _53_3_medicamentoadm3 VARCHAR(20) NOT NULL,
    _53_4_medicamentoadm4 VARCHAR(20) NOT NULL,
    _53_5_medicamentoadm5 VARCHAR(20) NOT NULL,
    _53_6_medicamentoadm6 VARCHAR(20) NOT NULL,
    _53_7_medicamentoadm7 VARCHAR(20) NOT NULL,
    _53_8_medicamentoadm8 VARCHAR(20) NOT NULL,
    _53_9_medicamentoadm9 VARCHAR(20) NOT NULL,
    _54_medicamentonopos1administrado VARCHAR(20) NOT NULL,
    _55_medicamentonopos2administrado VARCHAR(20) NOT NULL,
    _56_medicamentonopos3administrado VARCHAR(20) NOT NULL,
    _57_recibiquimioterapiaintratecal TINYINT NOT NULL,
    _58_fechafin1erciclo DATE NOT NULL,
    _59_caracticas1erciclo TINYINT NOT NULL,
    _60_mtivofinprematura1erciclo TINYINT NOT NULL,
    _61_ubitmpultciclomnejoonco TINYINT NOT NULL,
    _62_fechainiultimocicloquimio DATE NOT NULL,
    _63_noipssuministranultciclo SMALLINT NOT NULL,
    _64_codips1sumistraultciclo CHAR(12) NOT NULL,
    _65_codips2sumistraultciclo CHAR(12) NOT NULL,
    _66_ctosmedantineoplasicos SMALLINT NOT NULL,
    _66_1_medicamentoadm1 VARCHAR(20) NOT NULL,
    _66_2_medicamentoadm2 VARCHAR(20) NOT NULL,
    _66_3_medicamentoadm3 VARCHAR(20) NOT NULL,
    _66_4_medicamentoadm4 VARCHAR(20) NOT NULL,
    _66_5_medicamentoadm5 VARCHAR(20) NOT NULL,
    _66_6_medicamentoadm6 VARCHAR(20) NOT NULL,
    _66_7_medicamentoadm7 VARCHAR(20) NOT NULL,
    _66_8_medicamentoadm8 VARCHAR(20) NOT NULL,
    _66_9_medicamentoadm9 VARCHAR(20) NOT NULL,
    _67_medicamentonopos1administrado VARCHAR(20) NOT NULL,
    _68_medicamentonopos2administrado VARCHAR(20) NOT NULL,
    _69_medicamentonopos3administrado VARCHAR(20) NOT NULL,
    _70_rbioquimiointratecal TINYINT NOT NULL,
    _71_fechafinultciclo DATE NOT NULL,
    _72_cticasactultciclo TINYINT NOT NULL,
    _73_mvofinultciclo TINYINT NOT NULL,
    _74_stidousucirupaliativas TINYINT NOT NULL,
    _75_nocirugiasstidousu TINYINT NOT NULL,
    _76_fecha1racirugia DATE NOT NULL,
    _77_codips1racirugia CHAR(12) NOT NULL,
    _78_cod1racirugia VARCHAR(10) NOT NULL,
    _79_ubtmp1racirugiamnjoonco TINYINT NOT NULL,
    _80_fechaultproceqx DATE NOT NULL,
    _81_mvoultintervenqx TINYINT NOT NULL,
    _82_codipsultproceqx CHAR(12) NOT NULL,
    _83_codultcirugia VARCHAR(10) NOT NULL,
    _84_ubitmpultcirugiamnejoonco TINYINT NOT NULL,
    _85_estvitalfinultcirugia TINYINT NOT NULL,
    _86_rbiousuradioterapia TINYINT NOT NULL,
    _87_noesqmasradioterapia TINYINT NOT NULL,
    _88_fechaini1eresqradio DATE NOT NULL,
    _89_ubitmp1eresqradio TINYINT NOT NULL,
    _90_tipradioterapia1eresq VARCHAR(10) NOT NULL,
    _91_noipssumi1eresqradio TINYINT NOT NULL,
    _92_codips1sumtraradio CHAR(12) NOT NULL,
    _93_codips2sumtraradio CHAR(12) NOT NULL,
    _94_fechafin1eresqradio DATE NOT NULL,
    _95_cticas1eresqradio TINYINT NOT NULL,
    _96_mvofin1eresqradio TINYINT NOT NULL,
    _97_fechainiultesqradio DATE NOT NULL,
    _98_ubitmpultesqradio TINYINT NOT NULL,
    _99_tporadioultesqradio TINYINT NOT NULL,
    _100_noipssumtranultesqradio TINYINT NOT NULL,
    _101_codips1sumtranradio CHAR(12) NOT NULL,
    _102_codips2sumtranradio CHAR(12) NOT NULL,
    _103_fechafinultesqradio DATE NOT NULL,
    _104_caticasultesqradio VARCHAR(50) NOT NULL,
    _105_mvofinultesqradio TINYINT NOT NULL,
    _106_rbiotranscelulasprogtoras TINYINT NOT NULL,
    _107_tiptransrecibido TINYINT NOT NULL,
    _108_ubitmptransmnejoonco TINYINT NOT NULL,
    _109_fechatrans DATE NOT NULL,
    _110_codipsrelizotransplte CHAR(12) NOT NULL,
    _111_usurbiocirureconstiva TINYINT NOT NULL,
    _112_fechacirugia DATE NOT NULL,
    _113_codipscirreconstructiva CHAR(12) NOT NULL,
    _114_usuvalcdopaliativo TINYINT NOT NULL,
    _114_1_rbiocdopaliativoxesp TINYINT NOT NULL,
    _114_2_rbiocdopaliativoxprosalud TINYINT NOT NULL,
    _114_3_rbiocdopaliativoxotraesp TINYINT NOT NULL,
    _114_4_rbiocdopaliativoxmedge TINYINT NOT NULL,
    _114_5_rbiocdopaliativoxtrsocial TINYINT NOT NULL,
    _114_6_rbiocdopaliativoxotprosalud TINYINT NOT NULL,
    _115_fecha1racdopaliativo DATE NOT NULL,
    _116_codips1ravacdopaliativo CHAR(12) NOT NULL,
    _117_vdoxpsiquiatria TINYINT NOT NULL,
    _118_fecha1raxpsiquiatria DATE NOT NULL,
    _119_codipspsiquiatria CHAR(12) NOT NULL,
    _120_vdoxnutricion TINYINT NOT NULL,
    _121_fechavdoxnutricion DATE NOT NULL,
    _122_codipsnutricion CHAR(12) NOT NULL,
    _123_usurbiosrtenutricional TINYINT NOT NULL,
    _124_usurbioterrehabilita TINYINT NOT NULL,
    _125_tiptratamiento TINYINT NOT NULL,
    _126_resfinmjooncologico TINYINT NOT NULL,
    _127_estdovitalfincorte TINYINT NOT NULL,
    _128_novadmon TINYINT NOT NULL,
    _129_novclinica TINYINT NOT NULL,
    _130_fechadeseps DATE NOT NULL,
    _131_fechamuerte DATE NOT NULL,
    _132_causamuerte TINYINT NOT NULL,
    _133_idfosyga VARCHAR(20) NULL,
    _134_fechacorte DATE NOT NULL,
    mes VARCHAR(20) NOT NULL,
    anio SMALLINT NOT NULL,
    eapb VARCHAR(50) NOT NULL,
    apoyo VARCHAR(100) NULL,
    observaciones VARCHAR(MAX) NOT NULL,
    url_soporte_hc VARCHAR(500) NOT NULL,
    _add_fechainicioprimertto VARCHAR(50) NOT NULL,
    _add_tipotto_primertto VARCHAR(50) NOT NULL
);

ALTER TABLE res0247 ALTER COLUMN _29_estadiotnm VARCHAR(20) NOT NULL;

select * from res0247