
SELECT DISTINCT
	GENPACIEN.PACNUMDOC AS DOCUMENTO,
	CASE GENPACIEN.PACTIPDOC WHEN 1 THEN 'CC' WHEN 2 THEN 'CE' WHEN 3 THEN 'TI' WHEN 4 THEN 'RC' WHEN 5 THEN 'PA' WHEN 6 THEN 'AS' WHEN 7 THEN 'MS' WHEN 8 THEN 'NU' WHEN 10 THEN 'CN' WHEN 12 THEN 'PE' WHEN 14 THEN 'PE' WHEN 15 THEN 'PE' WHEN 9 THEN 'PE'
	ELSE 'NONE' END AS TIPO_DOC,
	GENPACIEN.PACPRIAPE AS APELLIDO1,
	GENPACIEN.PACSEGAPE AS APELLIDO2,
	GENPACIEN.PACPRINOM AS NOMBRE1,
	GENPACIEN.PACSEGNOM AS NOMBRE2,
	FORMAT(GENPACIEN.GPAFECNAC, 'yyyy-MM-dd', 'en-us') AS FECHA_NAC,
	GENTERCER.TERNOMCOM AS EAPB,
	GENOCUPACION.DGONOMBRE AS OCUPACION,
	GENCARGO.GCANOMBRE AS NIVEL_EDUCATIVO,
	GENARESER.GASNOMBRE AS INSTANCIA_ACTUAL,
	ADNINGRESO.AINTELACU AS TELEFONO,
	HCMHC25.HCCM01N48 AS [Tensión Arterial Sistólica (PAS)],
	HCMHC25.HCCM01N45 AS [Tensión Arterial Diastólica (PAD)],
	HCMHC25.HCCM01N43 AS [Frecuencia Respiratoria (FR)],
	HCMHC25.HCCM01N44 AS [Frecuencia Cardiaca (FC)],
	HCMHC25.HCCM01N75 AS [Peso],
	HCMHC25.HCCM01N47 AS [SPO2 (Oxígeno)],
	HCMHC25.HCCM01N46 AS [Temperatura],
	HCNFOLIO.HCFECFOL AS FECHA_FOLIO
FROM ADNINGRESO
	INNER JOIN HCNFOLIO ON HCNFOLIO.ADNINGRESO = ADNINGRESO.OID
	INNER JOIN GENPACIEN ON HCNFOLIO.GENPACIEN = GENPACIEN.OID
	LEFT JOIN GENDETCON ON GENPACIEN.GENDETCON = GENDETCON.OID
	LEFT JOIN GENTERCER ON GENDETCON.GENTERCER1 = GENTERCER.OID
	LEFT JOIN GENOCUPACION ON GENPACIEN.GENOCUPACION = GENOCUPACION.OID
	-- SELECIONE QUE SOLIO QUUIERE EXTRAER
	INNER join HCMHC25 on HCMHC25.HCNFOLIO = HCNFOLIO.OID
	LEFT JOIN GENARESER on HCNFOLIO.GENARESER =  GENARESER.OID
	LEFT JOIN GENCARGO on GENPACIEN.GENCARGO1 = GENCARGO.OID
	-- filtros
WHERE
	HCNFOLIO.HCFECFOL BETWEEN CONVERT(DATETIME, '2025-05-01', 120) AND CONVERT(DATETIME, '2025-09-16', 120)
	
	-- AND GENPACIEN.PACNUMDOC = '1234197484'
