-- QUIMIOTERAPIAS

WITH DatosQuimio AS (
    SELECT 
        GENPACIEN.PACNUMDOC AS HISTORIA,
        FORMAT(GENPACIEN.GPAFECNAC, 'yyyy-MM-dd', 'en-us') AS FECHA_NAC,
        CASE WHEN GENPACIEN.GPASEXPAC = 1 THEN 'M' WHEN GENPACIEN.GPASEXPAC = 2 THEN 'F' ELSE NULL END AS SEXO,
        CASE WHEN TRIM(GENPACIEN.PACPRIAPE) = '' THEN 'NONE'
             ELSE REPLACE(TRANSLATE(TRIM(GENPACIEN.PACPRIAPE), '·ÈÌÛ˙¡…Õ”⁄Ò—', 'aeiouAEIOUNN'), ' ', '')
        END AS PRIMER_APELLIDO,
        CASE WHEN TRIM(GENPACIEN.PACSEGAPE) = '' THEN 'NONE'
             ELSE REPLACE(TRANSLATE(TRIM(GENPACIEN.PACSEGAPE), '·ÈÌÛ˙¡…Õ”⁄Ò—', 'aeiouAEIOUNN'), ' ', '')
        END AS SEGUNDO_APELLIDO,
        CASE WHEN TRIM(GENPACIEN.PACPRINOM) = '' THEN 'NONE'
             ELSE REPLACE(TRANSLATE(TRIM(GENPACIEN.PACPRINOM), '·ÈÌÛ˙¡…Õ”⁄Ò—', 'aeiouAEIOUNN'), ' ', '')
        END AS PRIMER_NOMBRE,
        CASE WHEN TRIM(GENPACIEN.PACSEGNOM) = '' THEN 'NONE'
             ELSE REPLACE(TRANSLATE(TRIM(GENPACIEN.PACSEGNOM), '·ÈÌÛ˙¡…Õ”⁄Ò—', 'aeiouAEIOUNN'), ' ', '')
        END AS SEGUNDO_NOMBRE,
        FORMAT(HCMHC48.HCCM05N05, 'yyyy-MM-dd hh:mm', 'es-ES') AS FECHA,
        GENDIAGNO.DIACODIGO AS CIE10,
        GENDIAGNO.DIANOMBRE AS DX,
        HCMHC48.HCCM01N03 AS NRO_CICLOS,
        HCMHC48.HCCM04N04 AS ESQUEMA,
        GENTERCER.TERNOMCOM AS EAPB,
        CASE WHEN GENDETCON.GDEPOSSUB = 1 THEN 'SUBSIDIADO' 
             WHEN GENDETCON.GDEPOSSUB = 0 THEN 'CONTRIBUTIVO' ELSE '' 
        END AS REG_EAPB,
        ROW_NUMBER() OVER (PARTITION BY GENPACIEN.PACNUMDOC ORDER BY HCMHC48.HCCM05N05 DESC) AS RN
    FROM 
        ADNINGRESO
        INNER JOIN HCNFOLIO ON HCNFOLIO.ADNINGRESO = ADNINGRESO.OID
        INNER JOIN GENPACIEN ON HCNFOLIO.GENPACIEN = GENPACIEN.OID
        LEFT JOIN GENDETCON ON GENPACIEN.GENDETCON = GENDETCON.OID
        LEFT JOIN GENTERCER ON GENDETCON.GENTERCER1 = GENTERCER.OID
        INNER JOIN HCMHC48 ON HCMHC48.HCNFOLIO = HCNFOLIO.OID
        INNER JOIN HCNDIAPAC ON HCNFOLIO.OID = HCNDIAPAC.HCNFOLIO
        INNER JOIN GENDIAGNO ON GENDIAGNO.OID = HCNDIAPAC.GENDIAGNO
    WHERE 
        HCNFOLIO.HCFECFOL BETWEEN CONVERT(DATETIME, '2026-01-01 00:00:00', 120) AND CONVERT(DATETIME, '2026-01-05 00:00:00', 120)
		/*
        AND (
            LOWER(GENDIAGNO.DIACODIGO) LIKE '%c%'
            OR LOWER(GENDIAGNO.DIACODIGO) LIKE '%d%'
        )
        AND (LOWER(GENTERCER.TERNOMCOM) LIKE '%NUEVA%')
		*/
)

SELECT *
FROM DatosQuimio
WHERE RN = 1
ORDER BY FECHA;