SELECT DISTINCT
    ING.AINCONSEC AS INGRESO,
    ING.AINFECING AS [FECHA_INGRESO],
    ING.AINFECEGRE AS [FECHA_EGRESO],
    GENPACIEN.PACNUMDOC AS [NUM_HISTORIA_CLINICA],
    GENPACIEN.GPANOMCOM AS PACIENTE,
    GENTERCER.TERNOMCOM AS EAPB,
    -- Extracción de teléfono desde XML
    TRY_CAST(adinfpaci AS XML).value('(/HCCLInfoPaciente/@TELEF)[1]', 'nvarchar(400)') AS TELEFONO,
    -- Cálculo exacto de edad
    DATEDIFF(YEAR, GENPACIEN.GPAFECNAC, ING.AINFECING) - 
        CASE 
            WHEN (MONTH(GENPACIEN.GPAFECNAC) > MONTH(ING.AINFECING) 
                OR (MONTH(GENPACIEN.GPAFECNAC) = MONTH(ING.AINFECING) 
                AND DAY(GENPACIEN.GPAFECNAC) > DAY(ING.AINFECING))) 
            THEN 1 
            ELSE 0 
        END AS EDAD
FROM ADNINGRESO ING
INNER JOIN HCNFOLIO  ON HCNFOLIO.ADNINGRESO = ING.OID
INNER JOIN GENPACIEN ON HCNFOLIO.GENPACIEN   = GENPACIEN.OID
LEFT JOIN  GENARESER ON HCNFOLIO.GENARESER   = GENARESER.OID
LEFT JOIN  GENDETCON ON GENPACIEN.GENDETCON  = GENDETCON.OID
LEFT JOIN  GENTERCER ON GENDETCON.GENTERCER1 = GENTERCER.OID
WHERE 
    ING.AINFECING BETWEEN CONVERT(DATETIME, '2026-01-01', 120) AND CONVERT(DATETIME, '2026-01-08', 120)
    AND LOWER(GENARESER.GASNOMBRE) LIKE '%urgenc%'
    AND ING.AINFECEGRE IS NOT NULL;